### ISSUE TITLE
Create Template Sheets for common workflows or types of datasets

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#10]
- [ ] [open dialogue](https://docs.microsoft.com/de-de/office/dev/add-ins/develop/dialog-api-in-office-add-ins) box on first interaction 
- [ ] ask the user if they want to duplicate the current sheet (if present)
- [ ] [functionality to duplicate sheet](https://docs.microsoft.com/de-de/office/dev/add-ins/excel/excel-add-ins-worksheets#copy-an-existing-worksheet)

**Comment by Brilator** [comment]
@HajiraJabeen and I are actually planning to come from this perspective as well - to have quick solutions at hand for our colleagues. Maybe to coordinate this a bit - we'll focus first on RNASeq data (based on GEO guidelines) and metabolomics data (converging the CEPLAS metabolomics facilities with the MetaboLights requirements, which include ISA).

**Comment by kMutagene** [comment]
Sounds good! cc @omaus , maybe he can add some insight on the template sheets he's working on for proteomics

**Comment by omaus** [comment]
The template sheet I created is highly specific for mass spectrometry workflows (especially for the one used in our colleague's lab). Nevertheless, it might be interesting to compare both template sheets.
The proteomics template sheet can be found [here](https://github.com/omaus/ARC/tree/master/assays/proteomicsTemplate/assay.template).

**Comment by Brilator** [comment]
It'll be the same here - based on the existing samples submission templates of the metabolomics facilities associated with CEPLAS. In the end this is how we can propagate the tools / ideas through the back door (if people want to submit to the core facilities then, we'll just rub their noses into SWATE-ontology-enriched beautiful submission templates). 

Anyways, it'll take time. Also to get the people at the facilities involved. And also importantly to introduce data file conversion of proprietary mass spec raw data (i.e. towards mzTab). So looking forward to your workflows there.
