### ISSUE TITLE
[Feature Request] Update reference columns should remove non complete building block

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#102]
**Is your feature request related to a problem? Please describe.**
A user could delete the visible main column and the reference columns would stay. If we want to keep the "Update reference columns" logic, these need to be removed.

**Describe the solution you'd like**
Have "Update reference columns" remove uncomplete building blocks.

**Comment by Joott** [comment]
Alternatively, you could consider adding a "Delete Column" function which removes a column together with its reference columns. This way the problem you described ideally wont occur as long as columns are removed correctly.

**Comment by Freymaurer** [comment]
Done! Will be live with the next version (0.4.0)
