### ISSUE TITLE
[BUG] Protocol headers shifted to the right

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#108]
**Describe the bug**
After inserting a protocol through the upload protocol tool, the header is shifted one row to the right. 

In the picture: The header `peptide digestion` should span the three `parameters` instead of the `sample name`

![TableBug](https://user-images.githubusercontent.com/17880410/107774467-53ba0800-6d3f-11eb-9783-9ec4f4a70117.PNG)

**To Reproduce**
1. Create new `excel spreadsheet` and load swate `manifest.xml` as `add in`
2. Create new `annotation table` in swate
3. Click on cell `Source Name`
4. Load a protocol using the `protocol insert` function in swate

**Expected behavior**
The header should be spanned above the three parameters

**OS and framework information (please complete the following information):**
- Excel online
- Swate 0.3.0

**Additional context**
The CustomXML is correct, the problem seems to occur when rendering the information

![CustomXmlLog](https://user-images.githubusercontent.com/17880410/107775054-1a35cc80-6d40-11eb-8ab5-a034fa4bd971.PNG)

**Comment by Freymaurer** [comment]
This is a breaking bug, i will immediatly start working on it!

For now you can circumvent the bug by adding the table in EXACTLY row B.

**Comment by Freymaurer** [comment]
I have fixed the bug and will move it to production. Will update this issue as soon as it is live.

**Comment by Freymaurer** [comment]
Fixed and should be live!
