### ISSUE TITLE
Add Ribbon buttons and/or context menu buttons for the different application endpoints

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#11]
The addin functionality is exposed via hash based urls for different functionality e.g. /#TermSearch for the termSearch component. All Endpoints need a respective UI element in Excel. 

This would be much simpler when considering #8

**Comment by Freymaurer** [comment]
For now Swate navigation is more streamlined with a central entry button and in-app navigation. As i think #8 is too much effort for what we gain i think we should also close this issue for now. See issue #86 for some minor additional info on this topic.
