### ISSUE TITLE
[Feature Request] "Update unit" instead of "Add unit"

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#110]
**Is your feature request related to a problem? Please describe.**
At the moment, Swate doesn't allow (easily) to change the unit of a column. One would have to delete the column and add a new one with the desired unit.

**Describe the solution you'd like**
The "Add unit" button could be exchanged with an "Update unit" button that changes the unit if you like to.

**Describe alternatives you've considered**
None.

**Additional context**
![grafik](https://user-images.githubusercontent.com/47781170/107801520-7577b700-6d60-11eb-84c8-5fc029025932.png)

**Comment by Freymaurer** [comment]
Done! Will be part of version 0.4.0!
