### ISSUE TITLE
[Feature Request] File Picker Drag and Drop lines could be thicker

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#112]
**Is your feature request related to a problem? Please describe.**
Using the drag and drop feature in the file picker could look a little more responsive, as it's hard to see whether the dragged item gets inserted above or below the item hovered above.

**Describe the solution you'd like**
I think thicker lines representing the place of insertion would make it more visually responsive and self explanatory.

**Additional context**
![SwateFilePicker](https://user-images.githubusercontent.com/17880410/108211767-66608280-712d-11eb-9a56-264b220f6775.png)
Swate version 0.3.1

**Comment by Freymaurer** [comment]
Done!
