### ISSUE TITLE
[Feature Request] Easier addition of validation importance  

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#113]
**Is your feature request related to a problem? Please describe.**
In the "Validation" panel the slider for "importance" is nice, but I think it would be quicker to just freely type in a number of 1 - 100. And actually I think a 1-10 or only 1-5 score should suffice. 

**Describe the solution you'd like**
Radio buttons (rating stars) for 1 to 10 or 1 to 5. 

**Describe alternatives you've considered**
Enter value in free text box.

**Comment by Freymaurer** [comment]
Done! This will be added with version 0.4.0
