### ISSUE TITLE
[Feature Request] Show all child-terms

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#114]
**Is your feature request related to a problem? Please describe.**
If you use the (term-related) Search Term field, it only shows search results after typing in 3 letters.

**Describe the solution you'd like**
It would be nice if one could see all child-terms of the parent term already when clicking on the blank field.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Freymaurer** [comment]
Added option to double click into **empty** term search field. This will now show a scrollable drop down with **all** child terms.

This will be added in 0.4.0 and will need future refinement according to userfeedback.
