### ISSUE TITLE
[Feature Request] Compute "part_of" relations like "is_a"

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#116]
**Is your feature request related to a problem? Please describe.**
Many ontologies use parent terms that are interesting for our needs but their children are in a _part_of_ relationship to their parent instead of an _is_a_ relationship. Atm. Swate does not recognize _part_of_ relations as parent-child ones.

**Describe the solution you'd like**
_part_of_ relations are treated like _is_a_ relations.

**Describe alternatives you've considered**
Rebuild all ontologies with _part_of_ s replaced with _is_a_ s.

**Additional context**
Example of a _part_of_ relation, marked with the blue (P) logo:
![grafik](https://user-images.githubusercontent.com/47781170/108691126-6f6d9d00-74fb-11eb-8727-7c61497d8609.png)

From: https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001000&viewMode=All&siblings=false

**Comment by Freymaurer** [comment]
Done!
