### ISSUE TITLE
[BUG] Show all child terms not working for 'organism'

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#117]
**Describe the bug**
Trying to return all child terms (is_a) for organism returns a database error.

**Expected behavior**
Either return clear error or return some results.

**Additional context**
I still need to figure out how this error is produced. Until then i can' give any possible solutions.

**Comment by Brilator** [comment]
If this one is based on the NFDI4PSO:0000030 ( https://github.com/nfdi4plants/nfdi4plants_ontology/blob/main/nfdi4plants_ontology.obo) there are no child terms... 
I've added the requirement to the validation and in the obo I added 'organism' referring to the alt_id: http://www.ebi.ac.uk/efo/EFO_0000634. However, I haven't added the child terms.

**Comment by Freymaurer** [comment]
No this actually refers to: OBI:0100026; Which has, at least it feels like it, the whole ncbi taxon ontology as children (grandchildren, ...). 

That is why the function runs out of memory. Still not sure how to fix this.

**Comment by Freymaurer** [comment]
This will be handled via issue #193.
