### ISSUE TITLE
[Feature Request] Insert vertical ontology terms

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#118]
**Is your feature request related to a problem? Please describe.**
An additional metadata sheet was added to the assay file which is in ISATab format. Here some fields also require `ontology terms` (e.g. shown in the image below) which are cumbersome to fill out by hand. At the moment this can't be done by `Swate`, as there is no `annotation table` in this sheet and also the `TermName`, `TermAccessionNumber` and `TermSource` are `vertically` aligned instead of horizontally.

**Describe the solution you'd like**
Is there a way to use Swate for filling out these terms vertically, without them being in an annotation Table?

**Additional context**
![Vertical Terms](https://user-images.githubusercontent.com/17880410/108841007-6651fe00-75d7-11eb-9309-dd71983875c5.PNG)
Swate 0.3.1

**Comment by Freymaurer** [comment]
I will add a "Copy-to-Clipboard" option. Then you should be able to paste the term input with "Strg + v".

**Comment by Freymaurer** [comment]
Done! Will be part of 0.4.0!
