### ISSUE TITLE
[BUG;FB0.4.0] Remove Building Block removes Building Block even if you didn't select a Building Block

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#121]
**Describe the bug**
'Remove Building Block' button should remove a selected Building Block (via the selected column). If a cell of a column that does not have a Building Block is selected, it removes the Building Block furthest to the right.

**To Reproduce**
1. Create an Annotation table
2. Click on a cell or a column without a Building Block
3. Click 'Remove Building Block' (several times, if you want to)

**Expected behavior**
Should give an error message that no Building Block-owning column is selected.

**Comment by Freymaurer** [comment]
Fixed!
