### ISSUE TITLE
[Feature Request] More info for existing building blocks

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#124]
**Is your feature request related to a problem? Please describe.**
I couldn't reopen the issue #96. 

**Describe the solution you'd like**
Can you add more info about the linked annotation? Especially the "description" part, so that it is explicit enough for the user, why this annotation is there. 
This could also mitigate the need for commenting in excel cells. 

**Describe alternatives you've considered**
Link the TAN to the URL.

**Comment by Freymaurer** [comment]
Sry completly forgot to add the description.

**Comment by Freymaurer** [comment]
Done!
