### ISSUE TITLE
[Feature Request] Checksum as Checklist type

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#127]
**Is your feature request related to a problem? Please describe.**
Some repositories require a specific type of checksum for your raw data files (e.g. GEO requires MD5). 

**Describe the solution you'd like**
I know this is really shooting for the stars here... 
Implement MD5, sha256, etc. as validation type.

**Comment by Freymaurer** [comment]
Can you give some examples and screenshots where to add it? I am completly lost about what you mean :sweat_smile:

**Comment by Brilator** [comment]
![Screen Shot 2021-03-03 at 17 12 49](https://user-images.githubusercontent.com/16229676/109835881-e9acc880-7c43-11eb-8759-386adedcbc4b.png)

**Comment by Brilator** [comment]
As I said, that's pretty high level. But maybe there's a simple F# solution to at least check wether the value is a valid MD5 - without checking wether the calculated MD5 is also correct for the associated file.

**Comment by Freymaurer** [comment]
As Swate itself does not do any validation (that is something the arc commander will do) it is really easy for me to add more options at this position. 

Can you give me some more background informtion on what to add? I am thinking to add small on hover textboxes with a short description.

**Comment by Freymaurer** [comment]
Done! Will be part of the next live version.
