### ISSUE TITLE
[Question] Standard user vs. data steward 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#128]
**Is your feature request related to a problem? Please describe.**
More of a question: How do you make sure that validations are not changed by users? 

**Describe the solution you'd like**
Lock validation and allow only data stewards to edit.

**Comment by Freymaurer** [comment]
For now we still want to make sure users have as much freedom as possible. This also includes, sadly, the freedom to error.

In addition, we do not have a user autentication system up and running. This will have to wait for some time, until the basic system from Tübingen is ready.

I will close the issue for now, but you can open a discussion for this.
