### ISSUE TITLE
[Feature Request] Half-automated / controlled .json from SWATE templates. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#129]
**Is your feature request related to a problem? Please describe.**
Currently the .json pointers to the repository templates are written by hand and error-prone. 

**Describe the solution you'd like**
A small script to automatically pull out all existing info (names of workbook / sheet / annotationtable) from the xlsx template to avoid typos.

**Comment by Freymaurer** [comment]
As Excel does not allow Swate to offer something to download for the user i opted for a copy to clipboard solution:

![image](https://user-images.githubusercontent.com/39732517/109948459-a3ef0f00-7cda-11eb-9e2f-a5b64cc6e0c7.png)

![image](https://user-images.githubusercontent.com/39732517/109948537-b6694880-7cda-11eb-8c72-ecab97ed7bcf.png)

**Comment by Freymaurer** [comment]
Can be found: Settings -> Advanced Settings -> Data Stewards
