### ISSUE TITLE
Improve FilePicker functionality

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#13]
Necessary features:
- [x] Fill excel cells with file name(s)
- [x] ~~make file names from list selectable -> insert only selected~~
- [x] ~~fill column range with file names, extend range when file name list is larger than range~~

Edit: As of .. 

> Your approach filling only the selected range seems better to me.
> 
> > This seems like an extra step that will not be used regulary. As we currently allow users to remove unwated file names it is not necessary to select those you want to insert.
> 
> Are files taken by the order they are selected, or by the ordering of the explorer (e.g. alphabetical)? If the latter is true, at least reordering of the filelist must be possible if you are against selections. But you are right, we can take a minimal approach at all of this, as reordering can also be done via excel ui

- [x] Add option to reorder uploaded file names.

**Comment by Freymaurer** [comment]
Right now it starts to fill all selected cells from top down. If not enough cells are selected for all file names then only the selected cells are filled.

Exmp:
![image](https://user-images.githubusercontent.com/39732517/101396082-1cf0ed00-38cb-11eb-9c46-1fc96599db95.png)
![image](https://user-images.githubusercontent.com/39732517/101396098-224e3780-38cb-11eb-9f00-df3b26ef443f.png)

I am not sure if this makes sense, but we can discuss it @kMutagene .

My points for this are: 

> make file names from list selectable -> insert only selected
This seems like an extra step that will not be used regulary. As we currently allow users to remove unwated file names it is not necessary to select those you want to insert. What we could do, is to allow users to change the order of the filenames via drag 'n drop/small arrows.

> fill column range with file names, extend range when file name list is larger than range
As we currently have no 'revert changes' feature this could lead to a user deleting large parts of his file, should he select to many files and the table expend automatically. But then again this is what we do, whenever we add a building block to the column.

**Comment by kMutagene** [comment]
Your approach filling only the selected range seems better to me. 

> This seems like an extra step that will not be used regulary. As we currently allow users to remove unwated file names it is not necessary to select those you want to insert.

Are files taken by the order they are selected, or by the ordering of the explorer (e.g. alphabetical)? If the latter is true, at least reordering of the filelist must be possible if you are against selections

**Comment by Freymaurer** [comment]
Added a reorder drag and drop for all file names. Will be added in 0.1.4!
