### ISSUE TITLE
[Feature Request; kevinf-patch-0.4.1] Adding checksum column for validation

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#131]
references #127

As the file validation by a checksum requires the actual checksum strings for each file, it is not enough to just note in the table that a checksum is expected. Maybe an additional column could be added for this purpose.

This can be done as is:
- Go to `manage building blocks` menu
- Select `parameter` (or maybe `characteristic` would be better as it references the file) and find a proper checksum term (e.g. `Raw data file checksum`)
- Add the `checksum type` as a `unit` (`advanced unit search`, e.g. `MD5)`

**Describe the solution you'd like**

Then the needed connection between the checksum column and the sample name could be added via the validation menu:
- Go to `validation menu`
- Select `checksum column`
- Choose `checksum type` (this and the following would be new features)
- Dropdown opens showing all other columns
- Select the sample files or source files column the checksum referes to

**Comment by Freymaurer** [comment]
Done!
