### ISSUE TITLE
[Feature Request; kevinf-patch-0.4.1] Allow adding terms when no annotation table is present

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#132]
**Is your feature request related to a problem? Please describe.**
The `ISA.XLSX` `assay file` contains an additional metadata sheet, where some fields contains `ontology annotations` as values. These can handily be filled out using the `Swate` `Term picker`. Unfortunately the swate tool always expects an `annotationTable` to be present, which is not the case in the metadata sheet. 

**Describe the solution you'd like**
It would be good to allow the `term picker` to function regardless of a `annotationTable` being present in the `sheet`.

**Comment by Freymaurer** [comment]
Done!
