### ISSUE TITLE
[Feature Request] Metadata templates with drop-down selections

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#143]
**Is your feature request related to a problem? Please describe.**
Motivation a) User-friendliness. Lets user choose input values in anno building blocks directly from a list. 
Motivation b) Flexibility / independence of Excel and SWATE

**Describe the solution you'd like**
This is a solution between full SWATE+Excel (live linked to ontology and updated) and free-text input by user: 
1. Add an option (for data stewards) to export a SWATE annotated template with all term-related instances of the added building blocks e.g. stored in a separate sheet. 
2. Use the Excel "Data validation" feature to add the instances as drop-down list 

**Additional context**
Challenge a) Excel Templates need proper versioning and depending on the development of the (instances in the) added blocks frequent updates. 
Challenge b) TSR and TAN in the next columns need to be linked (e.g. vlookup). 

<img width="1017" alt="Screen Shot 2021-05-04 at 16 27 18" src="https://user-images.githubusercontent.com/16229676/117020304-9cf27600-acf6-11eb-99a5-138d95e57f14.png">
<img width="444" alt="Screen Shot 2021-05-04 at 16 28 41" src="https://user-images.githubusercontent.com/16229676/117020384-ada2ec00-acf6-11eb-9fa8-0a3274d9f56e.png">

**Comment by Freymaurer** [comment]
Sorry to only answer now to this issue. I tried to implement this quiet some time ago, but it was neither smooth nor did it feel really helpful. The Excel API does not give me the option to configure this in a useful way.
