### ISSUE TITLE
[Feature Request] Let SWATE auto-add annotationTable upon protocol insert 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#146]
**Is your feature request related to a problem? Please describe.**
Problem: convenience. 

**Describe the solution you'd like**
During protocol insert into an empty sheet, rather than showing the error `"Could not find annotationTable in active worksheet. Please create one before trying to execute this function."`, just automatically add an annotationTable.

**Comment by Freymaurer** [comment]
Done! This will be part of version `0.6.0` 🎉
