### ISSUE TITLE
[BUG] Excel online: hidden columns not inserted correctly when adding terms in columns not created via building block insert

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#149]
**Describe the bug**
Hidden columns (ontology source and term ref) are not inserted correctly in a blank new sheet in excel online

Not sure if this is a bug, as we might expect these columns to be added when adding building blocks. This only happens when inserting terms in single columns.

**To Reproduce**
1. open excel online
2. upload swate manifest.xml
3. insert annotation table
4. mark first column and search for a term to insert
	
	![image](https://user-images.githubusercontent.com/21338071/126318794-539cf8e1-4832-464f-ad2b-614c75b054d0.png)

5. Observe the error:
	![image](https://user-images.githubusercontent.com/21338071/126318866-7c495c1f-c617-471f-8d43-e7e9f2dc2fb2.png)

**Expected behavior**
Hidden columns get inserted for the two entries on the left, and sample column stays unaffected

**OS and framework information (please complete the following information):**
 - MS Excel: Excel Online

**Comment by omaus** [comment]
> Not sure if this is a bug, as we might expect these columns to be added when adding building blocks. This only happens when inserting terms in single columns.

I'd say it definitely is since some users might want to also fill the single columns with the `Fill selected cells with terms` function. If they shouldn't it should throw an exception whenever they try to.

**Comment by Freymaurer** [comment]
This is the same issue with issue #161. The term insert was meant to be as flexible as possible and is the only Swate function, which can be used without a Swate annotation table. 
This also leaves room for error, and i am not sure if the error possibility outweighs the option to use term insert more flexible.

**Comment by Freymaurer** [comment]
This issue will be addressed in version `0.6.0` 🎉
