### ISSUE TITLE
[BUG] Selecting header when using `Fill selected cells with terms` overwrites it

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#161]
**Describe the bug**
When selecting a header and using `Fill selected cells with terms` that header gets destroyed.

**To Reproduce**
1. Open Swate in a new excel file and create an annotation table (or destroy one you already worked with (not recommended))
2. Select the header (and cells below if you like)
3. Click on `Manage Terms`
4. Type in sth. on the blank field
5. Click on `Fill selected cells with terms`

**Expected behavior**
Only filling out non-header cells. Or throwing an exception if no non-header cells are selected.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/47781170/132880260-f8258564-5b96-4610-a356-b5c54817dc53.png)

After:
![image](https://user-images.githubusercontent.com/47781170/132880300-06471740-3b48-48e2-b067-4bc3f2be6eb6.png)

**OS and framework information (please complete the following information):**
- Swate v0.4.7
- Win10
- MS Excel 365

**Additional context**
Also happens when applying on columns that are not _source_ or _sample name_.
![image](https://user-images.githubusercontent.com/47781170/132880457-b5777cfd-1125-43f7-9f4e-a7792a3e18ac.png)

**Comment by Freymaurer** [comment]
This issue will be addressed in version `0.6.0` 🎉
