### ISSUE TITLE
[BUG] Improve instruction for MacOS installation

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#165]
**Describe the bug**
SWATE installation for MacOS is incomplete.  

1. The Installer (https://github.com/omaus/Swate_Install/raw/master/Installer/OSx/Install) does not work. 

2. Installing from latest release (https://github.com/nfdi4plants/Swate/releases/tag/v0.4.8) could need some more info:  
  a) To "Install node.js LTS (needed for office add-in related tooling)", please add the link: https://nodejs.org/en/download/
  b) The swate/swate.sh (from swate.zip) only has the `npx` line. Shouldn't it also install the dependencies  via `nom` as in Swate-0.4.8/tests/test.sh 

```
npm install -g office-addin-dev-certs
npm install -g office-addin-debugging
npm install -g office-addin-manifest
```

**Comment by Freymaurer** [comment]
We will soon have a new installer for mac, which should streamline installation by a lot! So expect a solution to this problem soon.

**Comment by Freymaurer** [comment]
All tries to create a robust Swate installer will be stopped for now. We instead focus on providing a Swate option without installation and getting Swate into the official microsoft add-in store.
