### ISSUE TITLE
[Feature Request] Export annotation table as process.json

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/Swate#168]
**Is your feature request related to a problem? Please describe.**
To support users in writing process.json files, as most find it easier to work with Excel files.

**Describe the solution you'd like**
Add an export function to swate. Then you would only need to fill an existing template or your own annotation table as one-liner and click on export.

**Comment by Freymaurer** [comment]
With version 0.5.0 it will be possible to export one table/all tables to process.json sequence/assay.json/table representation json format! 🎉
