### ISSUE TITLE
[BUG] Cannot add building blocks. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#170]
**Describe the bug**
...

**To Reproduce**
1. Go to "Templates" tab
2. Select template 
3. Click Add template
4. See error: `Invalid regular expression: invalid group specifier name`

**OS and framework information (please complete the following information):**
 - OS: MacOS 
 - OS Version: 11.6
 - MS Excel: Excel Desktop
 - MS Excel version: 16.54

**Comment by Freymaurer** [comment]
Excel 2019 compatibility will be tracked in #177 from now on, will close this issue.
