### ISSUE TITLE
[Feature Request] absolutely minor: Swate names on top (Core vs. Experts)

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#172]
**Is your feature request related to a problem? Please describe.**
When opening both Swate versions in parallel the tabs in the sidebar are both called "Swate". 

**Describe the solution you'd like**
Name the sidebar tabs "Swate Core" and "Swate Experts"

**Comment by Freymaurer** [comment]
We updated the Swate installation, which will propably fix this issue. Currently only the windows installer is finished but the mac version is in work!
