### ISSUE TITLE
[BUG] Adding a new Building Block to an existing Swate table returns error

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#180]
**Describe the bug**
When adding a new Building Block to an existing Swate table, sometimes the error "Unable to parse given string @ to TermMinimal.Name" gets returned. The Building Block won't be added to the table as a consequence.

**To Reproduce**
1. Open the attached .xsls file: [3ASY01_RNASeq.xlsx](https://github.com/nfdi4plants/Swate/files/7706463/3ASY01_RNASeq.xlsx)
2. Open Swate (Core)
3. Type sth. into the Parameter name 
4. Click on "Add Building Block"

**Expected behavior**
A Building Block is added to the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/47781170/145876336-7037c913-dc21-4b98-aee1-71015c93b656.png)

**OS and framework information (please complete the following information):**
 - OS: Windows 10 Home-64bit
 - OS Version: 10.0, Build 19042
 - MS Excel: Office 365
 - MS Excel version: 2111 (Build 14701.20226)

**Additional context**
Didn't happen when creating a new table (maybe backwards incompatibility?).

**Comment by Freymaurer** [comment]
I identified the error:

![image](https://user-images.githubusercontent.com/39732517/145956617-08445c2c-eb74-4ea5-a1fe-fd87cbd16859.png)

Swate was not able to handle any numberformat except units and the `General` number format, i added a failsafe to consider other options. This fix will be part of 0.5.2 .
