### ISSUE TITLE
[BUG] Swate install [collection]

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#181]
**Describe the bug**
Swtae installer too hardcoded in shared folder path. Needs to be done with flexible variable.

**Comment by Freymaurer** [comment]
If user is not admin and grants admin access: Swate creates folder in admin appdata:

![image](https://user-images.githubusercontent.com/39732517/146194195-d0ec4d71-6da7-4f18-bea7-b03d6f883fc4.png)

**Comment by elisenger** [comment]
Dear Freymaurer, I am trying to install Swate again , but the installer does not work. I use Excel 2019 and the installer that was present on 8-Dec is working, but not the new one you uploaded later. Any suggestions? I have uninstalled Swate and also cleared the cache folder as indicated, does not work anyway.

**Comment by Freymaurer** [comment]
> I am getting an error that makes no sense when I want to add new building blocks to an existing table with annotation blocks. This is why I want to install the newest version of swate.

> I use Excel 2019 and the installer that was present on 8-Dec is working.

I am not 100% sure, but there should be no Swate changes, which require a new installation, since 8-Dec. So we might need to look into the error.

**Comment by elisenger** [comment]
Great, thank you so much! I accessed the installer here: https://github.com/nfdi4plants/Swate/blob/developer/.assets/swate-win.zip?raw=true  When I double click on the installer-cmd, a commandline box pops up, put closes down after 1 sec without any result...

**Comment by elisenger** [comment]
I have downloaded the Plant growth data template with all annotation blocks. Now I want to add more blocks, for instance "Nitrogen fertilizer exposure". When I click on "add ann. block", the error I get says: "Swate encountered an error while processing the active annotation table.Swate found a reference column (Term Source REF [microeinstein per square meter per second] (#h; #tUO:0000160; #u)) with a core name (Term Source REF), that is already assigned to the previous building block.Building block main column: Characteristics [light intensity exposure], already assigned column: Term Source REF [light intensity exposure] (#h; #tPECO:0007224)"

**Comment by Freymaurer** [comment]
> When I double click on the installer-cmd, a commandline box pops up, put closes down after 1 sec without any result...

1. Open a fresh `Command Prompt` (Type `Command Prompt` in your windows search bar and it should show you the app)
2. <kbd>right click</kbd> on the Swate installer -> `Properties` . Then you can find the `Location` with a path to the folder in which the installer is.
3. Copy (<kbd>Ctrl</kbd> + <kbd>C</kbd>) this path.
4. Go back to your fresh `Command Prompt` and type `cd here\comes\your\path`, in which you will replace "here\comes\your\path" with the path you just copied. You can insert it with <kbd>Ctrl</kbd> + <kbd>V</kbd>. Press <kbd>Enter</kbd>, this will move the command prompt to the folder in which the installer is. 
5. Type `install.cmd` and press <kbd>Enter</kbd>. This will execute the installer without the window closing. 
6. Sorry for the difficulties, we are working on a more established installer.

> I have downloaded the Plant growth data template with all annotation blocks. Now I want to add more blocks, for instance "Nitrogen fertilizer exposure". When I click on "add ann. block", the error I get says: "Swate encountered an error while processing the active annotation table.Swate found a reference column (Term Source REF [microeinstein per square meter per second] (#h; #tUO:0000160; #u)) with a core name (Term Source REF), that is already assigned to the previous building block.Building block main column: Characteristics [light intensity exposure], already assigned column: Term Source REF [light intensity exposure] (#h; #tPECO:0007224)"

I think i might know the problem. When you say download, do you mean actually downloading the .xlsx Excel file? The error message references the old Swate tag array, which we stopped using a few months ago. So my guess is, you downloaded an old .xlsx file with the Swate table and the new Swate version can't handle that table.
IF that is the case, worry not you will have several options to solve this.

**Comment by elisenger** [comment]
Ok, I just opened a new excel file, imported the template annotation table and started to insert additional annotation blocks from scratch without problems. Maybe I was using an older template version, I´m not sure about the differences between the versions... Problem solved/avoided :) Thanks for you immediate help!

**Comment by Freymaurer** [comment]
You can always find the most recent templates in our template database and insert them right from Swate. These will always work! 


If you are not sure what i refer to, always feel free to ask 
Holen Sie sich Outlook für Android

**Comment by Freymaurer** [comment]
![image](https://user-images.githubusercontent.com/39732517/152881649-586ad28a-7ce1-4d31-ae64-b01a6d35486e.png)

**Comment by andreaschrader** [comment]
Can Swate 0.6.2 be used with Microsoft 365? During consulting we could not install this on a Windows Laptop. After installing, Swate could not be found inside Excel in the add-ins. Do we need to specifically place the manifest.xml somewhere?

**Comment by Freymaurer** [comment]
Hey! This should work with Microsoft 365. Have you looked here?
![image](https://user-images.githubusercontent.com/39732517/208915392-fe90bf84-c978-46b7-9a88-0bfcfd7896f2.png)

**Comment by andreaschrader** [comment]
Thanks, forwarded the information. I am very sure that we opened all 3 options and did not find Swate.
We downloaded "the latest version" from here: https://github.com/nfdi4plants/Swate/releases/download/v0.6.2/swate-win.zip

Maybe unrelated? Is 0.6.2 the correct current version? My installation from November tells me that it updated to v0.7.1.

**Comment by Freymaurer** [comment]
> I am very sure that we opened all 3 options and did not find Swate.

So you can replicate the image from my answer?

> Maybe unrelated? Is 0.6.2 the correct current version? My installation from November tells me that it updated to v0.7.1.

Swate is a webservice sideloaded in Excel. So even if you install 0.6.2 it will automatically update if it points to the correct url and Swate gets updated. So you should currently see Swate v 0.7.1

**Comment by Freymaurer** [comment]
All tries to create a robust Swate installer will be stopped for now. We instead focus on providing a Swate option without installation and getting Swate into the official microsoft add-in store.
