### ISSUE TITLE
[Feature Request] distinguish DataPLANT-curated vs. community-contributed templates

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#187]
**Is your feature request related to a problem? Please describe.**
With more templates contributed from external (community) data stewards, it would be helpful to distinguish DataPLANT-curated (i.e. those aligned with ER requirements and / or metadata checklists) vs. community-contributed templates (e.g. templates for very specific lab routines). 

**Describe the solution you'd like**
1. Add appropriate Tags "DataPLANT-curated" and "Community-contributed" to ontology (@Brilator) 
2. Add communities as Instances to ontology (@Brilator and others) 
3. Use these tags in SWATE template metadata tags list. (all template authors) 
4. Implement them in swate search / filter mechanism.

**Comment by Freymaurer** [comment]
let me know if the visual fits @Brilator @omaus . You can see an example [here](https://github.com/nfdi4plants/Swate/issues/186#issuecomment-1026903479).

**Comment by Freymaurer** [comment]
> However, for the time being searching, searching the community by tag would suffice.

I too think that is the best solution. If i make a dropdown filter for all communities this could become bloated really fast. Adn adding yet another search field would unnecessarily increase complexity while being redudant to a tag based search.

This will be implemented with the upcoming database update, as this will also affect Swobup.

**Comment by Freymaurer** [comment]
Now about the "How" to add information about `curated` vs `community` to the template metadata.

Any of:
1. `curated` and `community` are standard tags.
2. Make a special field `Curated` with true or false input.
3. Make special field with `curated` or `community` input. How should we call such a field to make it descriptive?

@Brilator @omaus @AngelaKranz

**Comment by omaus** [comment]
Maybe sth. alike to the special ER-Tags? Otherwise, I'd choose 1.

**Comment by Brilator** [comment]
Technically, 2 is probably least and and 3 less error-prone than 1. For 1 it could easily happen, that people add both tags (if they do not understand what they mean). 
Along the same lines, I would really call them "DataPLANT-curated" or "DP-curated", not just "curated". Templates coming from the community will likely still be curated (by the associated data steward), but not by DataPLANT (platinum flag ship templates...). 

To use solution 1, I would suggest to go one step further. 
Since you implemented the proper ontology fields, why not add it to our ontology with a proper definition. 

#TAGS list |  
-- | --
Tags | DataPLANT-curated
Tags Term Accession Number | NFDI4PSO:1000xxx
Tags Term Source REF | NFDI4PSO

#TAGS list |  
-- | --
Tags | community-contributed
Tags Term Accession Number | NFDI4PSO:1000xxx
Tags Term Source REF | NFDI4PSO

**Comment by Freymaurer** [comment]
I think we really should not use 1. then. If you can give more input on how you want 2. implemented, i can do that.

**Comment by Brilator** [comment]
Simplest solution for (2) would be to squeeze one key "Template source" in: 

![Screen Shot 2022-02-02 at 14 01 55](https://user-images.githubusercontent.com/16229676/152158803-8e580fc6-93a7-44c4-af4a-cb3175cdca78.png)
(example from 1SPL01_plants) 

And then only allow "DataPLANT-curated" or "community-contributed" (maybe find better categories, these are too long). 

I would not go for TRUE /FALSE, since this is a bit more literal.

**Comment by Freymaurer** [comment]
Done! This will be implemented in version `0.6.0` 🎉
