### ISSUE TITLE
[Feature Request] hover-over template metadata in database

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#188]
**Is your feature request related to a problem? Please describe.**
Tags template metadata are currently somewhat loose, undefined keywords. 

**Describe the solution you'd like**
To take full advantage of the ontology fields (Term, TSR, TAN) in the template metadata sheet, I would suggest to implement a feature to hover-over the tags supplied in the `ER list` and `tags list` (just as is the case for terms used in building blocks). 

This would simply allow to link towards external resources (e.g. repository website, if people do not know what GEO, ENA, PRIDE stands for) or the community (madland) or core facility (metabolomics lab), which supplies a swate template.

**Comment by Brilator** [comment]
#187

**Comment by Freymaurer** [comment]
So you would want to make tags links? Can you mockup how you would want this to look in the metadata sheet for the templates?

**Comment by Brilator** [comment]
I'd suggest to allow only ontology terms in tags and add everything that would make sense to be used as a tag to the / our / a ontology. 
I have on purpose not written below mock into the ontology. Just to show what I mean:

![Screen Shot 2022-07-25 at 10 24 07](https://user-images.githubusercontent.com/16229676/180733803-d71a2330-f35b-495d-aaa5-85794fe69d87.png)

```
format-version: 1.2
default-namespace: dataplanto
ontology: dataplanto
property_value: "has_website" xsd:string

[Term]
id: dataplanto:000001
name: Repository
def: "Repositories supported by DataPLANT" []

[Term]
id: dataplanto:000002
name: GEO
def: "GEO (Gene Expression Omnibus) is a public functional genomics data repository supporting MIAME-compliant data submissions. Array- and sequence-based data are accepted. Tools are provided to help users query and download experiments and curated gene expression profiles." []
property_value: has_website https://www.ncbi.nlm.nih.gov/geo/
is_a: dataplanto:000001 ! Repository

[Term]
id: dataplanto:000003
name: METABOLIGHTS
def: "MetaboLights is a database for Metabolomics experiments and derived information. The database is cross-species, cross-technique and covers metabolite structures and their reference spectra as well as their biological roles, locations and concentrations, and experimental data from metabolic experiments. MetaboLights is the recommended Metabolomics repository for a number of leading journals." []
is_a: dataplanto:000001 ! Repository
property_value: has_website https://www.ebi.ac.uk/metabolights/ xsd:string

[Term]
id: dataplanto:000004
name: PRIDE
def: "The PRIDE PRoteomics IDEntifications (PRIDE) Archive database is a centralized, standards compliant, public data repository for mass spectrometry proteomics data, including protein and peptide identifications and the corresponding expression values, post-translational modifications and supporting mass spectra evidence (both as raw data and peak list files). PRIDE is a core member in the ProteomeXchange (PX) consortium, which provides a standardised way for submitting mass spectrometry based proteomics data to public-domain repositories. Datasets are submitted to ProteomeXchange via PRIDE and are handled by expert bio-curators. All PRIDE public datasets can also be searched in ProteomeCentral, the portal for all ProteomeXchange datasets." []
property_value: has_website https://www.ebi.ac.uk/pride/
is_a: dataplanto:000001 ! Repository

[Term]
id: dataplanto:000005
name: DataPLANT Community
def: "Community associated to DataPLANT" []

[Term]
id: dataplanto:000006
name: CEPLAS
def: "Cluster of Excellence on Plant Sciences" []
property_value: has_website https://www.ceplas.eu
is_a: dataplanto:000005 ! DataPLANT Community

[Term]
id: dataplanto:000007
name: MAdLand
def: "Molecular Adaptation to Land: plant evolution to change" []
property_value: has_website https://madland.science
is_a: dataplanto:000005 ! DataPLANT Community

[Term]
id: dataplanto:000008
name: Metadata standard
def: "" []

[Term]
id: dataplanto:000009
name: MIAPPE
def: "Minimum Information About Plant Phenotyping Experiments" []
property_value: has_website https://www.miappe.org
is_a: dataplanto:000008 ! Metadata standard

[Term]
id: dataplanto:000010
name: MINSEQE
def: "Minimum Information about a high-throughput SEQuencing Experiment" []
property_value: has_website http://fged.org/projects/minseqe/
is_a: dataplanto:000008 ! Metadata standard

[Term]
id: dataplanto:000011
name: Measurement Type
def: "" []

[Term]
id: dataplanto:000012
name: Technology Type
def: "" []

[Term]
id: dataplanto:000013
name: Metabolomics
def: "" []
is_a: dataplanto:000011

[Term]
id: dataplanto:000014
name: Transcriptomics
def: "" []
is_a: dataplanto:000011

[Term]
id: dataplanto:000013
name: High-Throughput Sequencing
def: "" []
is_a: dataplanto:000012

[Term]
id: dataplanto:000014
name: Gas chromatography - Mass Spectromety
def: "" []
is_a: dataplanto:000012

[Term]
id: dataplanto:000015
name: Protocol Type
def: "" []

[Term]
id: dataplanto:000016
name: Plant Growth Protocol
def: "" []
is_a: dataplanto:000015

[Term]
id: dataplanto:000017
name: RNA Extraction Protocol
def: "" []
is_a: dataplanto:000015
```

![Screen Shot 2022-07-25 at 10 29 11](https://user-images.githubusercontent.com/16229676/180734024-a464965b-5063-493c-8c03-502e604795de.png)

I've added an annotation property "has_website". There might be a more official obo / owl annotation.
Swate could just check if the "tagged" term has the property "has_website" and then link to the website (rather than to ontology info as done for other terms already).

**Comment by Freymaurer** [comment]
Sorry for the misunderstanding! I must have lost my train of thought while typing!

The current Metadata Sheet for Templates looks like this:

![image](https://user-images.githubusercontent.com/39732517/180735286-3b8c4358-b5e1-4e6e-b956-c776ae4662e9.png)

According to:
- Requested split of tags and ERs.
- Confusion about `Authors Role`
- Organisation `DataPlant` will create `curated`-tag, everything else will create `community`-tag

Now to get back on track. What i really meant with my previous question was:

How would you want to include the ontology term information for the general user in the user interface? Because this is how tags and ERs are currently shown to the user: 

![image](https://user-images.githubusercontent.com/39732517/180735867-43ecfff9-6318-47b2-9345-44b5b464425d.png)

How would you like the information to be presented for the user for your example:

```
[Term]
id: dataplanto:000009
name: MIAPPE
def: "Minimum Information About Plant Phenotyping Experiments" []
property_value: has_website https://www.miappe.org
is_a: dataplanto:000008 ! Metadata standard
```

**Comment by Brilator** [comment]
What's wrong with how they are presented? 
I would mostly keep it that way. 
We could adapt the metadata sheet to more precisely ask for the individual categories (Repository, Protocol Type, Measurement Type, etc.) and then present those in different colors / groups.

**Comment by Freymaurer** [comment]
> What's wrong with how they are presented?

Well currently the only information shown to the user is: `name: MIAPPE`. Everything else exists only in the metadata sheet.

Your original issue was:

> **Describe the solution you'd like**
To take full advantage of the ontology fields (Term, TSR, TAN) in the template metadata sheet, I would suggest to implement a feature to hover-over the tags supplied in the ER list and tags list (just as is the case for terms used in building blocks).

**Comment by Brilator** [comment]
![Screen Shot 2022-07-25 at 10 53 39](https://user-images.githubusercontent.com/16229676/180737956-1155064d-f8cc-4856-be64-c388cad39b76.png)

Add an :information_source: icon with hover-over?

**Comment by Freymaurer** [comment]
If i do hover-over (over the term tags, as an ℹ️ icon would kill the ui with visual clutter) there is no:
> This would simply allow to link towards external resources (e.g. repository website, if people do not know what GEO, ENA, PRIDE stands for) or the community (madland) or core facility (metabolomics lab), which supplies a swate template.

As you cannot click on something in a tooltip (link) or copy it.

**Comment by Freymaurer** [comment]
Handled in #296
