### ISSUE TITLE
[Feature Request] Fill out assay/study sheet

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#202]
**Is your feature request related to a problem? Please describe.**
In the context of the `ARC`, we expanded the `Assay xlsx file` and `Study xlsx file` with a metadata containing `Assay` and `Study` sheet, respectively. 
These sheets also contain some ontology terms as values, which are tedious to fill out by hand.

**Describe the solution you'd like**
As `Swate` is the tool to fill out these files with ontology support anyway, it might be the best place for working on the assay sheet too?

**Additional context**
![image](https://user-images.githubusercontent.com/17880410/167801931-5db784c4-4e0d-45b8-8b0f-4957b9cbc560.png)
red boxes are ontology terms

**Comment by Freymaurer** [comment]
@HLWeil does this fit your feature request, so i can close the issue? 😄

**Comment by HLWeil** [comment]
Sorry for not responding earlier 😅 
Although this is a good easy solution, I'm actually not quite sure whether this is enough. In the long run, Swate could guide the user towards picking the correct terms (e.g. proposing terms having an `is a` relationship to `measurement type`) and directly insert them in the correct position.
The question is, could Swate even interpret and manipulate values that are not stored in an `annotation table`?

**Comment by Freymaurer** [comment]
It would be possible to rewrite the logic to use the first column of a sheet instead of the first row of a table.

This would lead to a more complext implementation, so this should be discussed in a future tools meeting.

**Comment by HLWeil** [comment]
Okay that's good to know. And I expected it to be more complicated to implement.

Also this is somewhat related to https://github.com/nfdi4plants/nfdi4plants_ontology/issues/32. Having some predefined `ISA` fields point to specific places in the `biological ontology`.
