### ISSUE TITLE
[BUG] `Upload protocol` does NOT work for MacOS

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#206]
**Describe the bug**
When using `Upload protocol` function, the chosen file does NOT get uploaded and cannot be inserted.

**To Reproduce**
1. Be on a Mac
2. Go to `Templates` tab
3. Click on `Upload protocol`
4. Choose your file
5. `Insert json` is still grayed out

**Expected behavior**
`Insert json` can be used.

**OS and framework information (please complete the following information):**
 - OS: MacOS

**Comment by Freymaurer** [comment]
Is this still an issue in Swate nightly? [swate-alpha](https://swate-alpha.nfdi4plants.org)

**Comment by Freymaurer** [comment]
Feel free to open this issue again, should it pop up again.
