### ISSUE TITLE
[Feature Request] API Requests to NFDI4Plants ontology

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#208]
SWATE has some capabilities to interrogate the NFDI4Plants ontology. Besides just getting terms by their name, one can also get related terms of a term of interest. E.g. when using the `Ontology term search` feature, child terms of the header term of the column are suggested. Features like this will also be useful in other, non SWATE applications. Like the ArcCommander converting ARCs to other metadata formats. Therefore I propose we move these features to a shared lightweight library.

**Comment by Freymaurer** [comment]
Will work on this tomorrow 👍

**Comment by Freymaurer** [comment]
https://github.com/Freymaurer/Swate.Api ✨
