### ISSUE TITLE
[BUG] install.cmd script not working when Windows username contains spaces

### ISSUE THREAD

**Issue by akirbis** [nfdi4plants/Swate#219]
**Describe the bug :**

We encountered a bug when installing the SWATE add-in for the Excel Desktop app using the install.cmd script in the swate-win.zip archive of the latest release. The shared folder that contains the two add-ins was not showing up in Excel for some people after running the installer. After some troubleshooting, it turned out that Windows user names that contain spaces mess up some functions of the install.cmd script.

By adjusting lines 6, 58, and 74 of the install.cmd script we were able to solve the problem for the moment. However, someone should check if the script is running as intended with the changes. I am attaching the modified file.

**To Reproduce :**

1. Create a Windows user with admin rights who has a space in his username (e.g. "Max Mustermann")
2. Change to the newly created user and download the swate-win.zip file from the latest SWATE release
3. Unpack the zip file and execute install.cmd
4. Open Excel, go to Insert>Add-ins. The shared folder tab that should contain the Core and Expert add-ins is not showing up.

**Expected behavior :**

Usernames containing a space should not impair the installer functionality

**OS and framework information (please complete the following information):**

 - OS: tested on Windows 10 and 11 with recent updates
 - MS Excel: Excel Desktop
 - MS Excel version: Excel 365

**Additional context**

Here's the modified install.cmd file (changed the file extension to be able to upload it here): 
[install.txt](https://github.com/nfdi4plants/Swate/files/9445566/install.txt)

**Comment by Freymaurer** [comment]
Hey! Nice catch! And thanks for your work, it is much appreciated! 

If you want some credit for your work, feel free to open a PR with your proposed changes. If not just tell me, then i'll push them for you.
