### ISSUE TITLE
[BUG] Small Ontology Term search field with long column header

### ISSUE THREAD

**Issue by Joott** [nfdi4plants/Swate#225]
When a large column header is chosen, the Ontology Term search field is displayed really small. Optimally, the width of the column header should have a maximal size to not decrease usability.

![image](https://user-images.githubusercontent.com/39764934/194325340-29b58aad-0ee3-4de6-bde1-982aef0b94d2.png)

**Comment by Freymaurer** [comment]
@zieglerSe this might be a nice first issue! Will transfer it to you.

**Comment by Freymaurer** [comment]
![image](https://user-images.githubusercontent.com/39732517/194887912-b7f272b4-7372-414a-aaf3-8509860e53e0.png)
Added a max width of 40% to the parent term field, on hover you can still see the full name.
