### ISSUE TITLE
[BUG] Term suggestion does not work with terms shorter than 3 chars

### ISSUE THREAD

**Issue by bvenn** [nfdi4plants/Swate#226]
When adding e.g. assay parameters of an experiment you have to type in at least 3 characters to get suggestions for the term ontologies. Often used terms (pH or g (g force)) cannot be found.

**Comment by Freymaurer** [comment]
I adjusted the search to trigger slower but on anything that is not only whitespace. This works well for ph but does not return the expected results for "g" (g force).

![image](https://user-images.githubusercontent.com/39732517/194882521-adcab055-8ed5-43c8-ac6f-3b807b693f32.png)

![image](https://user-images.githubusercontent.com/39732517/194882558-50878129-d305-474a-8cf7-0ce096990505.png)
