### ISSUE TITLE
[Feature Request] Checkboxes for large templates 

### ISSUE THREAD

**Issue by kdumschott** [nfdi4plants/Swate#227]
**Is your feature request related to a problem? Please describe.**
Minimal information standards often suggest 100+ parameters for properly annotating experiments. We are worried that including all terms in a template will overwhelm the user, but we also want to ensure the user is aware of terms that can be used when annotating their data.

**Describe the solution you'd like**
Begin able to select or deselect columns before adding the template to the annotation sheet could help solve this issue.

**Additional context**
As discussed at the Hackathon, there could also be an alternate solution of utilizing the converters to overhaul current template process but will need to be discussed at a later time (this issue is a reminder so this point does not get lost when we part ways).

**Comment by muehlhaus** [comment]
Maybe it is possible to separate these parameters into different worksheets. Worsheets represent logical process groups. By tagging the templates with the minimal information standard name in addition to a process name, users can find what is relevant...

**Comment by Freymaurer** [comment]
> An additional point to this is that in some checklists (for this instance, I am specifically referring to: https://genomicsstandardsconsortium.github.io/mixs/MIMARKSSpecimen/), checklist terms are either mandatory, optional or recommended. It may be useful to include this information in the corresponding Swate templates so researchers are aware of the importance/priority of the different parameters when creating their annotation sheets.

This part needs to be discussed by. Maybe during the next template meeting? If you could organize it @kdumschott ?

**Comment by Freymaurer** [comment]
We decided to push optional parameters for templates as additional templates, so this issue is obsolete 👍
