### ISSUE TITLE
[BUG] Duplicate terms appear when searching child terms in Swate Alpha

### ISSUE THREAD

**Issue by kdumschott** [nfdi4plants/Swate#230]
**Describe the bug**
When I search child terms to annotate my sheet, I get duplicate terms showing up

**To Reproduce**
1. Go to Excel and add the 'organism' heading using Swate Alpha
2.  Click on the row under the 'organism' heading and in the 'Ontology search term' window, search 'Arabidopsis'
3. See error: multiple terms with the same NCBITaxon ontology appear as options to select

**Expected behavior**
I would expect each option that appears to have a different term id and that duplicates will not be revealed

**Screenshots**
![NCBITaxonduplicateterms](https://user-images.githubusercontent.com/106731527/194516749-a9eaef40-24d1-4fca-a50c-3e196e92353b.png)

**OS and framework information (please complete the following information):**
 - OS: Windows 11 Pro

**Additional context**
I assume this has to do with multiple ontologies included in the SwateDB having the NCBITaxon term for Arabidposis imported into their own ontology and Swate Alpha is showing every one of these?

**Comment by Freymaurer** [comment]
Done! The changes go live with version 0.6.2. 🚀
