### ISSUE TITLE
[BUG] Adding a Unit to an existing building block changes formatting of cells

### ISSUE THREAD

**Issue by Joott** [nfdi4plants/Swate#231]
Adding a unit to a building block after it was created changes the formatting of the cells.
This is how it looks like before adding the unit:
![image](https://user-images.githubusercontent.com/39764934/194953976-070bda63-2b19-4d1e-b652-bf15906fdb40.png)
And this after adding a unit (to light intensity):
![image](https://user-images.githubusercontent.com/39764934/194954044-9071dd8d-24cd-491d-b9d5-ca45e53f1a48.png)
The hidden term accession numbers get unhidden and the parameter name is hidden instead. This can be fixed by autoformatting the table

**Comment by Freymaurer** [comment]
Fixed! Will go live with version 0.6.2 🚀
