### ISSUE TITLE
[Feature Request] Enable relative paths for file picker

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#233]
**Is your feature request related to a problem? Please describe.**
Files within an ARC are identified by their relative paths to the isa file. This means that when annotating computational workflows, input and output files must be annotated via relative paths (to the isa file). See https://github.com/nfdi4plants/ARC-specification/issues/59 for further insights/discussion.

**Describe the solution you'd like**
Easiest solution would be adding a text input field that can apply prefixes to all selected/copied file paths. A more sophisticated solution would automatically resolve relative paths from the current annotation file.

**Describe alternatives you've considered**
Well, you can use something like excels `CONCAT` function and copy the result into the original column but that's rather cumbersome and more of a workaround.

**Comment by Freymaurer** [comment]
Took me some time to get to this, but i created the logic for this to work under all operating systems, just to find out... Browsers do not give path information. For security reasons, which makes sense.

> Easiest solution would be adding a text input field that can apply prefixes to all selected/copied file paths.

I do not really see this as a useful alternative from both a UI or UX perspective, but i will enable the automatical path resolving in a future electron version.

**Comment by omaus** [comment]
Stupid question since I'm interested: Doesn't the File Picker return a full path?

**Comment by Freymaurer** [comment]
Only the name

**Comment by Freymaurer** [comment]
> Easiest solution would be adding a text input field that can apply prefixes to all selected/copied file paths.

~~The solution is back on the menu boys!~~
Will implement this solution 👍

**Comment by Freymaurer** [comment]
https://github.com/nfdi4plants/ARC-specification/issues/59

**Comment by Freymaurer** [comment]
This will be done as part of #383 in ARCitect only. Will close this for now 🙂
