### ISSUE TITLE
[Feature Request] Please provide installation instructions for any version for use with Excel on Mac.

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/Swate#234]
Please provide installation instructions for any version for use with Excel on Mac.

**Comment by Freymaurer** [comment]
All tries to create a robust Swate installer will be stopped for now. We instead focus on providing a Swate option without installation and getting Swate into the official microsoft add-in store.

You can have a look at the standalone version of Swate here: https://swate-alpha.nfdi4plants.org. This
