### ISSUE TITLE
[Fill down cells does not fill down the ontology terms ]

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#237]
**Describe the bug**
filling down a collumn with a cell does not transfer the ontology of the cell chosen to the cells filled down

**To Reproduce**
1. Go to 'some column with ontology attached'
2. Click on 'fill down for the whole table'
3. open the hidden ontology term
4. See error: no ontology term in the copied cells

**Expected behavior**

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/97098130/203796452-965fac30-89df-4ce5-a474-2e38fbd2b78a.JPG)

**OS and framework information (please complete the following information):**
 - OS: [Windows 10]

 - MS Excel: [365]
 - MS Excel version [only for Excel Desktop]

**Additional context**

![Unbenannt](https://user-images.githubusercontent.com/97098130/203796452-965fac30-89df-4ce5-a474-2e38fbd2b78a.JPG)

**Comment by frsommer** [comment]
also make all o-term fields text fields, so i can fill down the term without counting up teh o-term acc. number

**Comment by Freymaurer** [comment]
Did you use excel to extend the term for the lower rows? If yes click this button to update the reference (hidden) columns accordingly:

![image](https://user-images.githubusercontent.com/39732517/205051584-d23e10ff-f313-45e7-8ec7-f1b82a5889c3.png)

> also make all o-term fields text fields, so i can fill down the term without counting up teh o-term acc. number

What do you mean by this?

**Comment by frsommer** [comment]
yes with exel fill down, 
does not work with update button:

![image](https://user-images.githubusercontent.com/97098130/205092025-8fbee809-b9f7-4de0-882f-b80ccbca03c0.png)


with that fill down i mean this happens:
![image](https://user-images.githubusercontent.com/97098130/205092223-1b9b4e16-f5bf-4d01-bbd5-0dd166e66c36.png)

formating as text does not help, sorry, i just mean: is it possible to fix the fill down function to "copy" in these cells instead of standard "fill series"

**Comment by Freymaurer** [comment]
Sadly this is not possible, as this is a core excel functionality which i am not able to change 😞 But this issue will be solved in the upcoming standalone version of Swate. I already implemented a option for this behavior ✨ 

![image](https://user-images.githubusercontent.com/39732517/223466544-fdc4a2a8-c98a-442a-abcb-a5a57a355d8a.png)
