### ISSUE TITLE
[BUG] Minor: Space for "def" field in Ontology term search

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#238]
**Describe the bug**
There's some funny space in the "Ontology term search" tab, that should only pop up when clicking the down error (reserved for the term def). 

**Screenshots**
<img width="1317" alt="Screen Shot 2022-11-24 at 15 30 58" src="https://user-images.githubusercontent.com/16229676/203812395-cb92425d-8981-4ba5-8c5c-834014cdb199.png">

 
**OS and framework information (please complete the following information):**
 - OS: mac OS monterey
 - OS Version 12.3.1
 - MS Excel: Microsoft Excel for Mac v 16.67, Volume License 2019 (Desktop); same for Safari v 15.4

Swate v 0.6.2

**Comment by Freymaurer** [comment]
Does this bug still persist?

**Comment by Brilator** [comment]
It does. 
Swate v0.7.1 (did you share this with me directly?)

**Comment by Freymaurer** [comment]
Will handle this issue in #270
