### ISSUE TITLE
[Feature Request] Include base ontology for units

### ISSUE THREAD

**Issue by bvenn** [nfdi4plants/Swate#240]
I requested to add g-force into the ontology what happened [here](https://github.com/nfdi4plants/nfdi4plants_ontology/commit/e00ad7b823edcb10f8107f0ac25ce3dce1cf2050). But I cannot use g-force as unit because it does not recognize terms from the base ontology.

**Comment by Freymaurer** [comment]
For now please feel free to use the advanced term search to find `g-force` for the unit field. Will fix this asap #239

**Comment by Freymaurer** [comment]
This will be live on any version >0.7.1 ✨
