### ISSUE TITLE
ontology term link to ontobee no result

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#241]
**Describe the bug**
klicking in advanced search on the ontology term link, directs to ontobee site with nothing found

see pictures

searching in OLS: existing nicely, see picture

**To Reproduce**
1. Go to '.advanced search , choose MS ontology, search for triple, select Triple Quad 6500, click on ontology link..'

**Expected behavior**
see ontology description

**Screenshots**

**OS and framework information (please complete the following information):**
 - OS:  Windows 10
 
 - MS Excel: 365
 

**Additional context**
Add any other context about the problem here, like ideas for a solution.
[Doc2.docx](https://github.com/nfdi4plants/Swate/files/10122614/Doc2.docx)

**Comment by Freymaurer** [comment]
This is a bug on Ontobee, they say the include the ms ontology, but... https://ontobee.org/ontology/MS

As you can see, if you click any term it shows no result.

Maybe our ontology team @kdumschott @AngelaKranz can [get in contact](https://ontobee.org/contactus) with the maintainers of Ontobee to report this issue.

**Comment by kdumschott** [comment]
I will get in contact with Ontobee.

**Comment by Brilator** [comment]
We also ran into more dead links this morning @andreaschrader. 

Plus, we need to find a way to handle links to the DPBO, e.g. make persistently public (future) or default link to the OBO file (somewhat dirty).

**Comment by Freymaurer** [comment]
Will close this here for now. @Brilator @kdumschott please let me know if there is any new information on this topic.
