### ISSUE TITLE
Annotation table there but not recognized

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#242]
**Describe the bug**
Annotation table there but not recognized when not in A1 excel position

**To Reproduce**
1. Go to 'add template, not in first position A1'
2. still no table recognized
3. add annotation table

**Expected behavior**

**Screenshots**

**OS and framework information (please complete the following information):**
 -W10
 - Excel 365
**Additional context**
Add any other context about the problem here, like ideas for a solution.
![image](https://user-images.githubusercontent.com/97098130/204783487-a27411fa-e84e-4e54-a145-74b465c13af5.png)
![image](https://user-images.githubusercontent.com/97098130/204783523-c847a2c9-8b39-4f57-8f86-cc8caf1e8fba.png)

**Comment by Freymaurer** [comment]
How does this exactly happen? Did you create the table with this button?

![image](https://user-images.githubusercontent.com/39732517/204784468-edfcca05-81e8-489d-b593-ba20b107821f.png)

**Comment by frsommer** [comment]
sorry ich hab den bug gefunden:
man muss anscheinend erst ne table erstellen und kann erst dann das templat hinzufügen.

wenn man erst templat einfügt gibt es zwar ne komplette tabelle mit source und sample, die wird aber anscheinend nicht als solche erkannt...

auch in A1

**Comment by Freymaurer** [comment]
Die wird als Tabelle erkannt, nur das Warnfenster geht wahrscheinlich nicht weg. Versuch mal Swate zu schließen und neu zu öffnen wenn du über das Template eine Tabelle erstellst. Dann sollte das Warnfenster nicht auftauchen.

Nur beim start wird einmal überprüft ob bereits eine Tabelle auf dem worksheet vorhanden ist.

**Comment by frsommer** [comment]
alles klar, muss gar nix speichern zumachen etc, hab jetzt das kleine schließen kreutzchen an dem war-fenster gesehen, hatte erwartet das das automatisch schließt wenn kein fehler da ist.
danke
