### ISSUE TITLE
Need semicolon separated multi-input for single cells

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#243]
**Is your feature request related to a problem? Please describe.**
e.g. My cells are treated with ampiciline and kanamycine and...

how to add these terms in a single cell without need to duplicate the row?

need e.g. 
column header: Parameter[abiotic plant exposure] 
with input in the single cell: ampiciline; kanamycine;..;..

otherwise i would have to duplicate the row and add to the first row Parameter[abiotic plant exposure] ampicilline, to the second row Parameter[abiotic plant exposure] kanamycine ... etc and finally combine all in one source and one sample.
this gets extremly user-unfriendly when i try to design complex, mor component experiments

**Describe the solution you'd like**
need e.g. 
column header: Parameter[abiotic plant exposure] 
with input in the single cell: ampiciline; kanamycine;..;.. that is semicolon separated multi-input for same column 

**Describe alternatives you've considered**
see above

**Additional context**
thanks

**Comment by muehlhaus** [comment]
Header duplication is also not the nicest option...we have to think about that. However, you can add another Sheet and add the parameter there... A button like "continue on next sheet" might make this senario more user-friendly. 
Maybe something else also comes to mind...

**Comment by Freymaurer** [comment]
If input and output are the same in one sheet and we continue on another sheet, in isa-json it will be handled as one sheet. So i don't see the solution in this.

**Comment by Freymaurer** [comment]
Allowing multiple duplicate building blocks again in the next Swate version > 0.6.3 ✨ 
![image](https://user-images.githubusercontent.com/39732517/206191486-c5986597-ed28-4752-aef1-9000d4a372b7.png)
