### ISSUE TITLE
ontology term description empty

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#245]
**Is your feature request related to a problem? Please describe.**
some ontology term descriptions are empty this is not very nice (in my oppinion the opposit of ontology term).
this might have happened when terms are imported

**Describe the solution you'd like**
If ontology terms are empty ask the person who wanted that term includet for a description, might hafe to make a new term then, or even more complicated???

**Describe alternatives you've considered**
create new term in NFDI ontology? with description

**Additional context**

**Comment by Freymaurer** [comment]
Any examples?

**Comment by frsommer** [comment]
![image](https://user-images.githubusercontent.com/97098130/204826440-c2cb0368-948c-450e-8fd9-0e843284b2f8.png)
hier sind drei

**Comment by frsommer** [comment]
i see...
and is it possible to see the DPBO in a tree view with the dependencies?
when i click the link on the term i get an funny xml sheet where i cannot find the term nor the accession number?
![image](https://user-images.githubusercontent.com/97098130/204834715-a307cf3d-a41f-41d5-af71-449f973e85a4.png)
