### ISSUE TITLE
[BUG] Ontology DB Api getTermSuggestions returns hits in strange order

### ISSUE THREAD

**Issue by Thyra** [nfdi4plants/Swate#247]
**Describe the bug**
When searching for an incomplete species name (e.g. *Arabidopsis thali*), getTermSuggestion firstly returns all kinds of crosses/derivatives of Arabidopsis thaliana but as results are limited, not the species I am looking for itself. That only appears as the first hit when I have typed in the full name. This apparently happens for all species, I have not tested other ontologies.

**To Reproduce**
1. Go to https://swate.nfdi4plants.org/
2. Search for 'Arabidopsis thal'
3. See results

**Expected behavior**
I would expect 'Arabidopsis thaliana' as the first hit and all the others.

**OS and framework information (please complete the following information):**
Ontology DB Api - v2 (0.0.1) (OAS3)

**Additional context**
We are currently creating a MIAPPE-Wizard (https://github.com/IPK-BIT/miappe-wizard) so I'm not using the Excel Plugin but rather the REST API at https://swate.nfdi4plants.org/docs/IOntologyAPIv2.html itself.

**Comment by Freymaurer** [comment]
I added an additional sorting step and it should now return the results in the correct order.

The whole issue is explained [here](https://stackoverflow.com/questions/75018528/neo4j-fulltext-search-dont-score-same-word-multiple-times) with additional sandbox setup information.

This will be part of the next release (>7.1).
