### ISSUE TITLE
Exel freezes

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#249]
**Exel freezes**
Exel freezes when searching something like a parameter header in building blocks

**To Reproduce**
1. Go to swate
2. Click on Building blocks, then Parameter, then search :concentration, see the dropdown list, click in the Table (left), Excel freezes
'

**Expected behavior**
work on

**Screenshots**
![image](https://user-images.githubusercontent.com/97098130/212859416-178494aa-7613-429d-9478-655053001ecd.png)

**OS and framework information (please complete the following information):**
 -  Windows 10
 - OS Version [e.g. 1809] 
 - MS Excel: [365

**Additional context**
Add any other context about the problem here, like ideas for a solution.

**Comment by frsommer** [comment]
but seems not really reproducible, just had that issue a couple of times now

**Comment by frsommer** [comment]
but also freezes during search...
so just slow?

**Comment by frsommer** [comment]
yes, random freezing these days

**Comment by Freymaurer** [comment]
Would you mind sending me the affected .xlsx file?

**Comment by frsommer** [comment]
[Swate ProteinWorkFlow Template_fs1_MK_OM_fs.xlsx](https://github.com/nfdi4plants/Swate/files/10434263/Swate.ProteinWorkFlow.Template_fs1_MK_OM_fs.xlsx)

**Comment by Freymaurer** [comment]
I clicked around for some bit, but for me everything seems to be working fine. No freezes, no slow search. Please watch out for any patterns you might observer and let me know. Then i can look into this again.

**Comment by Freymaurer** [comment]
Will close this issue for now if it reappears, feel free to reopen.
