### ISSUE TITLE
[Feature Request] Make available terms searchable / visible

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#261]
Originally posted [here](https://github.com/nfdi4plants/SwateDB/issues/4)

**Is your feature request related to a problem? Please describe.**
In a consulting meeting this morning where we introduced Swate, we had a user who would like to be able to search or look through **all** available terms in "the ontology" (i.e. SwateDB in this case). 

**Describe the solution you'd like**
Something similar to [OLS](https://www.ebi.ac.uk/ols/index). 
Some kind of visual ontology browser, where you can really scroll and dive through the hierarchy of an ontology. 

**Additional context**
Use case: (a) if unsure which of similar / synonymous terms to use, or (b) what alternatives could make sense. Swate's advanced search isn't quite it as it only yields matching terms and doesn't visualize the big picture. 
Our answer was mostly, if you do not find a term: use free-text and / or request the term at ontology. 
But I can see that this still could make sense, maybe even in terms of curating the DPBO.

**Comment by Freymaurer** [comment]
Please bring this up on the next tools meeting, i think this is above the scope of Swate and could be a tool on its own.

**Comment by Brilator** [comment]
Can you perhaps transfer the issue to dpbo? thanks
