### ISSUE TITLE
[BUG] Protocol type column is missing

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/Swate#263]
GEO minimal templates were created together with the protocol type column, as this is required information by the repository.
After selecting such a template in Swate, the protocol type columns is not shipped with the remaining template, but missing.

**Comment by Martin-Kuhl** [comment]
I just tested and the column is still missing.

**Comment by Freymaurer** [comment]
Which template does contain a protocol type column?

**Comment by Martin-Kuhl** [comment]
For example all of [these](https://github.com/nfdi4plants/Swate-templates/tree/main/templates/dataplant/GEO).

**Comment by Freymaurer** [comment]
Found the problem and fixed it, do we also want protocol ref as part of templates?

**Comment by Martin-Kuhl** [comment]
Would make sense imo. Is this also something you on your side would need to change? We would also need to update the templates..
