### ISSUE TITLE
[BUG] Export Swate conform xlsx file not working 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#264]
**Describe the bug**

**To Reproduce**
1. Go to Swate Expert tab "Json Exporter"
2. The functions under "Export Swate conform xlsx file." at bottom
3. Choose any option (Assay, ProcessSeq, ProtocolTemplate) from drop down
4. (try to) click "Download as isa json"
5. See error

`"Could not read assay from stream: Archive file cannot be size 0." @/api/IISADotNetCommonAPIv1/toAssayJsonStr.`

**OS and framework information (please complete the following information):**
 - OS: MacOS
 - OS Version Ventura 13.2
 - MS Excel: Both - Excel MacOS Desktop and Excel Online (MS Edge)

**Comment by Brilator** [comment]
Related to #256?

**Comment by Freymaurer** [comment]
Can you sent me the .xlsx file which triggered the error?

**Comment by Brilator** [comment]
Nevermind. Confused the function with the "Export active table" above... and did not "upload an xlsx" to begin with. Sorry.

**Comment by Freymaurer** [comment]
Oh but there is still a check missing, You should not get any response while the button is red.

Does your cursor look like this when hovering above the button on mac? 🚫

**Comment by Brilator** [comment]
yes!

**Comment by Freymaurer** [comment]
Okay I'll add an additional check, so it won't even trigger an error.

**Comment by Brilator** [comment]
Suggestion: let it trigger an error, but state clearly what's missing (upload file first). Same for the other options above.
