### ISSUE TITLE
Check for usable API sets depending on function used

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#27]
Many functions in the Office.js API need a minimum version of Excel. when using more recent APIs, it is necessary to catch the case where the user has an old excel version so that the function call doesn't fail. An example can be seen [here](https://docs.microsoft.com/de-de/office/dev/add-ins/excel/excel-add-ins-tables), where the auto-resize of columns is API set specific.

**Comment by Freymaurer** [comment]
Swate gives an descriptive error if a function of unavaiable API set is used. We have a feature list comparing Swate usability for Excel 2019 and newer versions.
