### ISSUE TITLE
[BUG] Swate Experts in macOS desktop: json exporter not working

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#271]
**To Reproduce**
1. Go to Swate Expert tab "Json Exporter"
2. The functions under "Export active table" or "Export workbook"
3. Choose any option (Assay, ProcessSeq) from drop down
4. (try to) click "Download as isa json"
5. See no json being downloaded to Downloads folder (this is where I would expect it, right?) 

**OS and framework information (please complete the following information):**
 - OS: MacOS
 - OS Version Ventura 13.2
 - MS Excel: Excel MacOS Desktop version 16.69.1
- Runtime: Safari WebKit Version: 0.6.2.0

**Comment by Freymaurer** [comment]
This works in Excel online and standalone, but not in Excel 2019 for mac. Will close for now.
