### ISSUE TITLE
[Feature Request] links to new docs

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#272]
Once moving the user docs is finished https://github.com/nfdi4plants/nfdi4plants.knowledgebase/pull/89 and https://github.com/nfdi4plants/Swate-docs/pull/4

- [x] remove wiki contents
- [x] add links to new user docs and dev docs in 
  - [x] https://github.com/nfdi4plants/Swate#readme
  - [x] https://github.com/nfdi4plants/Swate/wiki

**Comment by Freymaurer** [comment]
Can you tell me the current state of the swate docs transfer?

**Comment by Freymaurer** [comment]
Done!
