### ISSUE TITLE
[BUG] Ctrl+"Autoformat Table" not working on macOS

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#273]
Just FYI, the option to "Hold Ctrl and click the Autoformat Table quick access button to adjust column widths and un-hide all hidden columns." does not work on macOS. 

https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/QuickStart_swate_walkthrough.html#showing-ontology-reference-columns

**Comment by Freymaurer** [comment]
Does it show any error message? Can you show me console output during the operation?

**Comment by Brilator** [comment]
Console stays blank. 

Problem is likely different mapping of macOS function keys (e.g. copy = <kbd>command</kbd> + <kbd>c</kbd>)

<kbd>command</kbd> + left click = behaves just like left click (auto format hides columns)
<kbd>option</kbd> + left click = behaves just like left click (auto format hides columns)
<kbd>option</kbd> + left click = behaves like right-click (context menu)

**Comment by Freymaurer** [comment]
Ah this is actually good to know, i will check for this.

**Comment by Freymaurer** [comment]
Should be fixed on > Swate-alpha06. On mac you might be able to hold<kbd>control</kbd> or <kbd>command</kbd> now, let me now if it works or not 😄

**Comment by Brilator** [comment]
Cannot find the `auto format hides columns in 0.8.0-alpha06

**Comment by Freymaurer** [comment]
Yeah not yet released, it will be live in 0.8.0-alpha07. Just adding more stuff currently 👍
