### ISSUE TITLE
[Feature Request] unify wording "Create annotation table" 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#274]
Button in yellow popup (Warning: No annotation table found in worksheet) says "Create annotation table", while Quick Access button says "Add Annotation Table". 

- [x] I'd suggest to unify them both to "Create annotation table". 
- [ ] Would require updates in docs though

**Comment by Freymaurer** [comment]
I am not really up to date on the current state of the docs. Would you be so kind to update the relevant docs for the namechange to "Create annotation table"? @Brilator
