### ISSUE TITLE
[Discussion] Building Block with Term and/or Unit

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#281]
I am not 100% sure how to handle the following case:

Let's say we have any building block created with a unit. Can this building block only contain numbers/free text input in its main column? Or can it contain another term as value?

See the example below:

| Parameter [Something]    | Unit    | TSR  | TAN                             |
|--------------------------|---------|------|---------------------------------|
| instrument model my_unit | my_unit | unit | http://urltounit/unit_000000000 |
| 12 my_unit               | my_unit | unit | http://urltounit/unit_000000000 |

Is it allowed to add something like instrument model to a unit block?

@muehlhaus @Martin-Kuhl @Brilator @HLWeil

**Comment by Martin-Kuhl** [comment]
So far, I cannot imagine a scenario where I would not want to put a number in front of a unit. For user-friendliness, e.g., when using a template, I would still allow to add terms as values, as Swate ignores the unit in such cases (or at least does not add it to the cell). If this however can be a problem when parsing the table, maybe an option could be that Swate automatically removes the unit when an ontology term is added?

**Comment by HLWeil** [comment]
Shouldn't be a problem when parsing the table to ISA-Json.

**Comment by Freymaurer** [comment]
I used your input to make term search more flexible in standalone mode. This will now update column header, unit or term depending on the selected column ✨
