### ISSUE TITLE
[swate-alpha] Add assay metadata sheet

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#298]
Swate standalone should feature a metadata sheet.

As far as i can see this sheet can have two types of metadata.

1. The main case, an assay metadata sheet
2. A template metadata sheet #257

Must templates also contain an assay metadata sheet? I am not sure about this one @Brilator @Martin-Kuhl 

If they must not contain an assay metadata sheet, i will handle these as "any of" case. And will not support adding both to one xlsx file in Swate standalon.

**Comment by Martin-Kuhl** [comment]
From my perspective, templates do not need an assay metadata sheet. I think the current process (adding them via AC) is sufficient.

**Comment by Brilator** [comment]
If we're talking about the isa.investigation-style Assay sheet: should not be added by Swate (templates).

**Comment by Freymaurer** [comment]
Just to be sure, i am talking about this assay metadata sheet:

![image](https://user-images.githubusercontent.com/39732517/224373041-2d6c9f66-e9cf-4f75-b448-6e6b7a7a1f38.png)

**Comment by Brilator** [comment]
Yes. Swate should not add this (as of now).
1. Swate is also relevant for isa.study (-> sheet "Study")
2. Few of the information (if any) would be templated.
