### ISSUE TITLE
Add Generator form for high level metadata

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#30]
While current abstractions should work well for study and assay parts of the ISA model, the investigation part which contains metadata about authors, publications etc. associated with the study is not supported currently. Using excel for that seems impractical though, a better alternative may be a full screen form modal inside of excel triggered by the web app, which then from the input generates a new tab and/or file containing this metadata.

**Comment by kMutagene** [comment]
Possibly a feature that better belongs into the [ArcCommander tool](https://github.com/nfdi4plants/arcCommander). will leave open for discussion.

**Comment by Freymaurer** [comment]
I think this issue is currently tackled by @HLWeil for the ArcCommander.
