### ISSUE TITLE
[BUG] add `protocol type` links to wrong TSR, TAN 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#304]
**OS and framework information (please complete the following information):**
 - OS: macOS ventura 13.3
 - MS Excel: Excel Desktop

**Describe the bug**

When adding a protocol column `Protocol Type`, the search field (e.g. to parameter, characteristics, factor) needs to be blank. Otherwise the `Protocol Type` adds the TSR and TAN result of that last search to the `Protocol Type` building block.

**Comment by Freymaurer** [comment]
This is most likely resolved in the newest version.
