### ISSUE TITLE
[BUG] "Protocol template must contain exactly one template"

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#305]
**OS and framework information (please complete the following information):**
 - OS: macOS ventura 13.3
 - MS Excel: swate alpha Standalone

**Describe the bug**
1. open template database tab
2. Click e.g. “Plant growth”, “Metabolite Extraction” template
3. template metadata (author, date, description, etc.) appears
4. Click `select` 

Error: 
```
"Protocol template must contain exactly one template" @/api/ITemplateAPIv1/getTemplateById
```

**Comment by Brilator** [comment]
This bug is related to Protocol columns (Protocol REF and Protocol Type). 
These columns may not have a (mix of) value(s) in them.
Test WIP

**Comment by Brilator** [comment]
cannot assign @Freymaurer

**Comment by Brilator** [comment]
1. having all cells in the `Protocol Type` building block filled out with the same values **works**

Protocol Type | Term Source REF (DPBO:1000161) | Term Accession Number (DPBO:1000161)
-- | -- | --
plant growth protocol | DPBO | http://purl.obolibrary.org/obo/DPBO_1000164
plant growth protocol | DPBO | http://purl.obolibrary.org/obo/DPBO_1000164
plant growth protocol | DPBO | http://purl.obolibrary.org/obo/DPBO_1000164


https://github.com/nfdi4plants/Swate-templates/commit/2d2bc6febd5fbc817d9e59036254e18c0ee7ef18

2. same also **works** for `Protocol REF`

Protocol REF
--
plant-growth.txt
plant-growth.txt
plant-growth.txt
plant-growth.txt
plant-growth.txt
plant-growth.txt



https://github.com/nfdi4plants/Swate-templates/commit/e6bd8d411a3f03f24d3042662d61e517ea0d83d6

**Comment by Brilator** [comment]
That means: there can (currently) be no mixed values in protocol type and protocol REF, which at least for the template should also not be the case. However a blank value is also different from a non-blank. 
So if one supplies example values, these must be the same in all cells.

**Comment by Freymaurer** [comment]
With the change to ARCtrl this issue is resolved!
