### ISSUE TITLE
[BUG] installation link is down

### ISSUE THREAD

**Issue by SaibotMagd** [nfdi4plants/Swate#309]
The link you provide to download Swate is offline: [swate installation link](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/SwateManual/Docs01-Installing-Swate.html)

**Comment by Freymaurer** [comment]
Hello, sorry for the inconvenience! where did you find this link?

Here is the correct one: https://nfdi4plants.github.io/nfdi4plants.knowledgebase/docs/SwateManual/Docs01-Installing-Swate.html

**Comment by SaibotMagd** [comment]
thx

**Comment by Freymaurer** [comment]
> where did you find this link?

So i can fix the broken link 😅
