### ISSUE TITLE
[Feature Request] allow custom units

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#310]
[user feedback]

**Is your feature request related to a problem? Please describe.**

UO is pretty limited and obviously allows only "standard" units (although questionable). 

**Describe the solution you'd like**
Might help to allow custom (i.e. free-text) units (just like "user-specific" any input). 

**Additional context**
The example was: unit "days after sowing (DAS)" to annotate plant age. 
Pragmatically much better than not having clarified what age is meant or using a generic unit e.g. "day".

**Comment by Freymaurer** [comment]
This should be possible with swate-alpha
