### ISSUE TITLE
[Feature Request] Prevent (excel)auto formatting / suggest format

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#312]
[user feedback]

**Is your feature request related to a problem? Please describe.**
Excel tries to help with guessing number formats (e.g. dates). 

**Describe the solution you'd like**
Similar (but maybe simpler) to the checklist, allow pre-determining the value format (maybe based on Excel's category choice) in swate templates.

<img width="133" alt="Screenshot 2023-06-14 at 12 58 32" src="https://github.com/nfdi4plants/Swate/assets/16229676/0f46884f-335a-441c-93de-9b28e8b7e945">

**Additional context**
Example:
- Used template that asked for number input (no unit associated)
- RIN numbers 8.7 => July 8th

**Comment by Freymaurer** [comment]
Will close this for now, feel free to reopen. But it is so far from the current scope i do not even understand it anymore 😅
