### ISSUE TITLE
installation guide link in README.md is broken.

### ISSUE THREAD

**Issue by eik-dahms** [nfdi4plants/Swate#314]
The link to the swate installation page in the readme file, found under the headline Install/Use, seams not to work. Leads to 404.

link is:
https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/SwateManual/Docs01-Installing-Swate.html

**Comment by Freymaurer** [comment]
Hello, sorry for the inconvenience! Thanks for reporting the dead link!

Here is the correct one: https://nfdi4plants.github.io/nfdi4plants.knowledgebase/docs/SwateManual/Docs01-Installing-Swate.html

**Comment by SaibotMagd** [comment]
The links for quickstart, walkthrough and documentation are also dead.

**Comment by Freymaurer** [comment]
Thanks for bringing this to our attention! I replaced the dead links with the correct ones!
