### ISSUE TITLE
[BUG] Term search takes excessive amount of time

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#315]
**OS and framework information**
 - OS: Windows 11
 - MS Excel: Excel Desktop

**Describe the bug**
I have a Parameter of this type: https://ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C16275

And am looking for the following term, which is a child term: https://ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C17429

But the term search looks like this for a long time (1-2 Minutes):
![image](https://github.com/nfdi4plants/Swate/assets/17880410/28827036-b60d-4021-91b2-6337d383c4ce)

In works eventually:
![image](https://github.com/nfdi4plants/Swate/assets/17880410/b10d2885-355a-4175-99f6-458bcfb7e185)

**Comment by Freymaurer** [comment]
Same for "Research technology"

**Comment by Freymaurer** [comment]
Also check "instrument model" -> "pegasus" or "instrument model" -> "triple"

**Comment by Freymaurer** [comment]
handled in: #332
