### ISSUE TITLE
[Feature Request] More ISA-tab-like Inputs and Outputs

### ISSUE THREAD

**Issue by WaljaWanney** [nfdi4plants/Swate#316]
### Problem
In the ISA-tab study and assay files, there is a strict differentiation between Source, Sample, and Extract (etc), and Protocols. In contrast, in SWATE, each input is considered a source, and each output is treated as a sample. Consequently, a sample in one file can be or must be the source of another file.

The way SWATE is right now, it is encouraged to always use Source Name as input, while the input for an ISA-tab assay file would usually be Sample Name, and the output would be e.g. Extract Name.

### Solution
Adding more Input/Output options.

### Additional context
This is related to my issue # 63 in Swate-templates https://github.com/nfdi4plants/Swate-templates/issues/63

**Comment by andreaschrader** [comment]
I would like to leave a comment: 
Personnaly I like this solution and naming.

and suggestion to the image you shared above:
Adding 'RessourceDataFile' already as a suggestion for the input would be very helpful and provide orientation:
Projects use unpublished input files from others that they are allowed to use for their project, place in the ressources directory and use these in their scripts within the ARC.
 
I also see the 'FreeText' option. However, questions on this are reoccuring. Therefore my suggestion.

**Comment by HLWeil** [comment]
`Extract` might be a good addition. It does have an explicit representation in ISA-Json too.

**Comment by UrsulaE** [comment]
It is still not clear to me how this is supposed to be translated into real live examples. If there are already templates that follow this format with Input[...] and Output[...] columns, please point the users towards them. 

It is still not clear to me how this is supposed to be translated into real live examples. As the isa specification is that sources must be specified in a column called "Source name", same for sample and "Sample name", it could either e.g. be Source name[Image file], or should there be additional columns called Input[] or Output[] that are neither in the categories Parameter, Characteristic, Factor, Component nor Protocol. Presumably, if an entire workflow was to be represented by a single Study or Assay, there could be several Input and Output columns in a table? Would then Source name and Sample name represent the initial input and final output? Or are we still with the only one source and sample column policy?

**Comment by Freymaurer** [comment]
Here is a link to the ISA-XLSX specification: https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#inputs-and-outputs (thanks to @HLWeil )

Should this not answer your questions feel free to ping me 😄

**Comment by Freymaurer** [comment]
Done for now! Until we update the IOTypes available!
