### ISSUE TITLE
[Feature Request] Order of columns is potentially important

### ISSUE THREAD

**Issue by WaljaWanney** [nfdi4plants/Swate#317]
### Problem
The order of the columns in SWATE is relevant if for example multiple Protocols are used on one Source to create a Sample. The order of columns also helps in clarifying that Characteristics are related to Materials (Source, Sample, etc) while Parameters, Components, and Factors are related to Protocols.

| Source Name | Characteristic [] | Protocol REF | Parameter [A] | Component [A] | Protocol REF | Parameter [B] | Component [B] | Sample Name |
|---|---|---|---|---|---|---|---|---|
| ...| ... | ...| ... | ...| ... | ...| ... | ...|

In the current parsing logic from and to ISA-JSON column order is irrelevant

### Additional context
Related to https://github.com/nfdi4plants/Swate-templates/issues/63

**Comment by HLWeil** [comment]
Hey @WaljaWanney, 

thanks for your input. From the user feedback we got, people like to mix the order of Parameters, Chracteristics and Factors. ISA-JSON does not support this out of the box as (as you stated) the columns are sorted into different places of the process object. We tried to keep this information when parsing to and from ISA-Json by adding the `ColumnOrder` comment. 

Regarding the ProtocolREFs: We don't currently support multiple `Protocol REF` columns at all in one xlsx sheet. They are needed to distinguish different protocols in `isa_assay.tab` files. But in `isa_assay.xlsx` files, these protocols are separated via the xlsx file sheets. Adjusting the specification accordingly is on the bucketlist.

**Comment by WaljaWanney** [comment]
Thank you for the clarification, very interesting.
So when I use two protocols to go from a Source to a Sample, my options are either naming the intermediate and use two sheets:
1st Sheet: Source -> ProtocolA -> SampleA
2nd Sheet SampleA -> ProtocolB -> SampleB
or put the Protocols together into one, which has the constraint that i cannot use the same Parameter twice:
Source -> ProtocolAB -> Sample

E.g I grow my plants in a pre-culture (ProtocolA) then in the larger volume culture (ProtocolB), from which I take my Samples, I cannot use the term e.g. Parameter [Growth Medium] twice in the same sheet, instead I have to use two sheets and name the intermediate.

I think this is a restriction I can life with :)

Thanks again for the insight.

**Comment by Freymaurer** [comment]
> or put the Protocols together into one, which has the constraint that i cannot use the same Parameter twice:

There are cases in which you can use the same term columns twice (at least Swate allows this). An example for this might be a "Component [Peptidase]", where you can have multiples in one protocol.

> E.g I grow my plants in a pre-culture (ProtocolA) then in the larger volume culture (ProtocolB), from which I take my Samples, I cannot use the term e.g. Parameter [Growth Medium] twice in the same sheet, instead I have to use two sheets and name the intermediate.

I think in this case you would need to use multiple worksheets 👍 Swate imports the output from your last worksheet as new input if you hold `Ctrl` while left-clicking "Add new table".

> I think this is a restriction I can life with :)

Glad to hear! If there is anything unclear or you would like to see improved, tell us about it!
