### ISSUE TITLE
[Feature Request] Add TS4TIB Ontology server

### ISSUE THREAD

**Issue by sneumann** [nfdi4plants/Swate#320]
Hi,

**Is your feature request related to a problem? Please describe.**
https://service.tib.eu/ts4tib/ is a Terminology Service (TS) building on the OLS software system, including an API that is OLS compatible.
While OLS is mainly targeting the life-sciences, the ts4tib provides a Terminologies for many more disciplines.

**Describe the solution you'd like**
It would be great if Swate would support multiple backends, including online queries to OLS and TS4TIB.
The API descriptions are at https://service.tib.eu/ts4tib/swagger-ui.html and https://www.ebi.ac.uk/ols4/help

**Additional context**
This might also reduce the maintenance burden if the TS4TIB and OLS could serve what currently needs SWOBUP.

Yours,
Steffen

**Comment by AngelaKranz** [comment]
Hi, 
we had a few discussions about it during the CorDI. 
It would be cool to consider it for our DataPLANT ontologies. I would suggest to discuss this in more detail in meeting(s).

**Comment by Freymaurer** [comment]
Yes we already got in contact!

**Comment by Freymaurer** [comment]
handled in: #332
