### ISSUE TITLE
Development of SWATE suspended?

### ISSUE THREAD

**Issue by UrsulaE** [nfdi4plants/Swate#323]
A comment on https://github.com/nfdi4plants/Swate/issues/321 by Freimaurer from 15 Nov 2023 suggests that the development of Swate is currently suspended. It would be helpful to add a comment in the knowledge base on the nfdi4plants page, ideally replacing the dead link for Swate Dev Docs in the nfdi4plants knowledge base.

It might also have implications for users of Swate and users/creators of (curated) Swate templates, who will be wondering whether the tables they create with Swate are still up to date.

**Comment by Freymaurer** [comment]
> It might also have implications for users of Swate and users/creators of (curated) Swate templates, who will be wondering whether the tables they create with Swate are still up to date.

Swate templates will be usable from the ARCitect soon, so development on the templates will not be wasted.

**Comment by Freymaurer** [comment]
@Brilator

**Comment by Freymaurer** [comment]
Swate is back in active development as it is now an active partner of ARCitect! 🎉
