### ISSUE TITLE
[BUG] dead links in SWATE Info

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#327]
**OS and framework information (please complete the following information):**
 - Windows 11
 - MS Excel: Excel Desktop
 - Swate 0.7.1

**Describe the bug**
- Dead links in the SWATE Info box
- If you click full documentation and also user documentation you get an 404 Error (https://nfdi4plants.github.io/Swate-docs/index.html) 

![Screenshot 2024-01-02 135147](https://github.com/nfdi4plants/Swate/assets/127506066/109ed9ab-26ad-4afb-b95c-f6c310740e34)

**Comment by Freymaurer** [comment]
fixed for alpha version
