### ISSUE TITLE
Backend dev mode instructions

### ISSUE THREAD

**Issue by joshmoore** [nfdi4plants/Swate#328]
Before these instructions get wiped from the Elixir Slack after 90 days, I wanted to capture the instructions that @Freymaurer helped me to compose as a quick start for backend development:

* Install the 1.6 .NET SDK (I was doing this on a clean Intel Mac)
* clone this repo (*duh*)
* Run `dotnet tool restore`
* Run `npm install`
* Run `dotnet run --project build/Build.fsproj run` which starts `.db/docker-compose.yml`. If this fails for some reason, bring it up yourself with `docker-compose up` from that directory.

Once running, localhost 3000 is swate, 8000 is swobup

**Comment by Freymaurer** [comment]
Added to readme!
