### ISSUE TITLE
[Bug]: swate template issues in ARCitect 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#329]
### What happened?

Cannot add templates
    - select templates from database
    - click add template
    - see error: `Protocol AddAnnotationBlocks is not implemented. Replace template logic first`

### Host

ARCitect

### Host Details

- arcitect v0.026
- macOS 14.1

### Swate version

1.0.0-alpha.01

**Comment by Freymaurer** [comment]
Done! Live after version 1.0.0-alpha.01 ✨
