### ISSUE TITLE
[Bug]: uploading protocol fails 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#330]
### What happened?

  - click upload protocol, select swate-created.json
  - "insert json" button inactive
  - after click on inactive button, error: `'SpreadsheetInterface.ImportFile' is not implemented`

### Host

ARCitect

### Host Details

- arcitect v0.0.26
- macOS 14.1

### Swate version

1.0.0-alpha.01

**Comment by Freymaurer** [comment]
Will close this for now. Protocol json upload is not yet restored and is postponed to an unknown datetime 😅
