### ISSUE TITLE
[Feature Request]: swate warning, when trying to add building block to "Metadata"

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#333]
### Is your feature request related to a problem?

swate default opens on sheet "Metadata". Trying to add a building block does not do anything.

### Describe the solution you would like!

Get a warning: you cannot add building blocks to the "Metadata" sheet

### Host

ARCitect

### Host Details

arcitect v0.0.26

**Comment by Freymaurer** [comment]
For now solved in commit https://github.com/nfdi4plants/Swate/commit/87e815254ed48e979d76329b4a619948ef9e0f54 . Live in versions higher than 1.0.0-alpha.01
