### ISSUE TITLE
[Feature Request]: add note on deleting single (not all) tables

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#335]
### Is your feature request related to a problem?

Users might click trash button only to delete one table.

### Describe the solution you would like!

add note on how to delete one table 

### Host

Standalone

### Host Details

Swate Release Version [1.0.0-alpha.01](https://github.com/nfdi4plants/Swate/releases) Host Browser

**Comment by Freymaurer** [comment]
Done, thanks for the help!
