### ISSUE TITLE
[Bug]: disable options to create Investigation / Template inside ARCitect

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#337]
### What happened?

When opening an isa.assay / isa.study in ARCitect and force-deleting the existing table(s), Swate offers the option to create a New File incl. Investigation and Template, which would not make sense in that context. 

### Host

ARCitect

### Host Details

ARCitect v0.0.26

### Swate version

1.0.0-alpha.01

**Comment by Freymaurer** [comment]
> force-deleting the existing table(s)

Uhh, thats a leftover logic from when i did not have a metadata sheet! Good catch. Deleting all tables should not reset the files!

**Comment by Freymaurer** [comment]
Done! Will be fixed from v1.0.0-alpha.02 ✨
