### ISSUE TITLE
[Bug]: term directed search not working in ARCitect

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#338]
### What happened?

- Selected a building block (organism) 
- Ontology term search tab does not trigger to search inside organism 

### Host

ARCitect

### Host Details

v0.0.26

### Swate version

1.0.0-alpha.01

**Comment by Freymaurer** [comment]
This is true for all current Swate alpha versions! Will fix

**Comment by Freymaurer** [comment]
Should be fixed vor alpha.02! Will release soon
