### ISSUE TITLE
[Bug]: term-directed search only active from row 2 and below 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#339]
### What happened?

- select a building block in swate table
- got ontology term search 
- click cell in first row -> nothing
- click cell in second row -> term directed search triggered 

### Host

Standalone

### Host Details

- macOS 14.1 
- Safari, Firefox, edge 

### Swate version

1.0.0-alpha.01

**Comment by Freymaurer** [comment]
Should be fixed vor alpha.02! Will release soon
