### ISSUE TITLE
[Bug]: Swate cannot convert specific tables to xlsx

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#346]
### Contact Details

issue

### What happened?

1. ARCitect: new ARC – new Assay – `Edit Table`
2. Swate View: Select sheet – go to Templates tab – browse database – select template – add template ✅ 
3. ARCitect: `Save ARC` – get error and loading circle 

![Screenshot 2024-01-29 at 10 50 20](https://github.com/nfdi4plants/Swate/assets/16229676/926512aa-6b71-491b-943b-8a02a71f4719)

### Host

ARCitect

### Host Details

ARCitect v0.0.26

### Swate version

1.0.0-alpha.03

**Comment by Freymaurer** [comment]
i verified that this issue is not ARCitect related, but an issue of Swate in itself. The logic to write the existing table to xlsx will break under specific circumstances. 

For now, adding the `DNA extraction` template without any body cell input will lead to this issue. I will further investigate

**Comment by Freymaurer** [comment]
issue was at its core created by a falsely set flag. should be fixed in the next release!
