### ISSUE TITLE
[Bug]: Cannot save file without building blocks 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#355]
### Contact Details

issue

### What happened?

The following error pops up, when trying to save (download) an isa table or template, for which only top-level metadata was filled out.

> Collection was empty.\nParameter name: list

### What did you expect?

More verbose warning (something like "Your isa table does not contain any building blocks"), but still download the file 

### Host

Applies to All

### Host Details

Standalone 

### Swate version

v1.0.0-alpha-08 Host Browser

**Comment by Freymaurer** [comment]
This issue will soon be handled correctly by ARCtrl without any error messages!

**Comment by Freymaurer** [comment]
Thanks to @HLWeil for fixing this in ARCtrl ✨
