### ISSUE TITLE
[Feature Request]: add note to Excel plugin referring to current state and alternatives

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#357]
### Contact Details

issue

### Is your feature request related to a problem?

The swate plugin is currently a bit out-dated (compared to standalone and ARCitect)

### Describe the solution you would like!

Pop-up / info box on top when activating swate plug-in. 
"The Excel plugin is currently being updated. For latest features check-out [Swate in your browser](https://swate-alpha.nfdi4plants.org) or integrated in [ARCitect](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/ARCitect-Manual/index.html)

### Host

Excel

### Host Details

Any Excel Desktop (and browser?)

**Comment by Freymaurer** [comment]
This is more difficult than you might expect. I could make a release from a previous version but it will still point to our only main release url.

So either ARCitect and standalone get a new url or i have to "kill" swate in excel and replace it with only this message and no more functionality.

**Comment by Brilator** [comment]
Bummer, I thought this could be an easy alternative for the time being

**Comment by Freymaurer** [comment]
Excel development will be taken up hopefully next month by a new collegue 🎉 Will close this issue for now!
