### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/Swate#366]
### Contact Details

h.doerpholz@fz-juelich.de

### What happened?

I was using /api/IOntologyAPIv2/getAllTermsByChildTerm (with "Name": "tropical mangrove" and "TermAccession": "ENVO:01000403") and among the results (see the attached file) I could see three of our own terms referenced with NFDI4PSO (e.g. NFDI4PSO:0002008) instead of the DPBO terms. What database is the API accessing that these terms are still being returned? That shouldn't be possible anymore. Since we want to work with the DataPLANT ontology service this issue is quite important to us since we need to know the relationships of terms inside the database.

[response_1707896805244.json](https://github.com/nfdi4plants/Swate/files/14276596/response_1707896805244.json)

### What did you expect?

At the most, I expected DPBO terms instead of NFDI4PSO terms (in addition to all other retrieved entries), if they were still linked to my query term the same way (which I don't believe they are, going by the related term search in Swate). One of the results is "environment (feature)" (NFDI4PSO:0002008). This term also exists in DPBO (DPBO:0002008), but there are no child terms linked (as opposed to the NFDI4PSO term), since it shows no children in the tree view and also doesn't return any children using the API /api/IOntologyAPIv2/getAllTermsByParentTerm.

### Host

Excel

### Host Details

Web Version Excel, Ubuntu 22.04 LTS

### Swate version

Ontology DB Api - v2   0.0.1   OAS3; Swate v1.1.0-alpha.10

**Comment by Freymaurer** [comment]
Hello! It uses the database setup from Swobup. I already contacted marcel to remove the nfdi4pso from the database and he updated swobup to not read in the nfdi4pso again. After checking i found around 500 terms from nfdi4pso still in the database. These were now removed and should never appear again. Feel free to open another issue (reopen) if you should find another nfdi4pso term.

**Comment by Freymaurer** [comment]
> At the most, I expected DPBO terms instead of NFDI4PSO terms (in addition to all other retrieved entries), if they were still linked to my query term the same way (which I don't believe they are, going by the related term search in Swate). One of the results is "environment (feature)" (NFDI4PSO:0002008). This term also exists in DPBO (DPBO:0002008), but there are no child terms linked (as opposed to the NFDI4PSO term), since it shows no children in the tree view and also doesn't return any children using the API /api/IOntologyAPIv2/getAllTermsByParentTerm.

Regarding this part, i was not informed about any changes in the ontology structure, you might need to open this as a new issue in the nfdi4plants_ontology repository

**Comment by Hannah-Doerpholz** [comment]
Awesome, thank you for the quick fix! I'll ask Kathryn regarding the structure
