### ISSUE TITLE
[Bug]: open external links in new browser window / tab

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#369]
### What happened?

The link in the File Export tab 

> Export Swate annotation tables to official ISA-JSON ([more](https://isa-specs.readthedocs.io/en/latest/isajson.html#)).

should open in a fresh browser window / tab. 

This is especially annoying when clicking inside ARCitect: displays right in there and there's no way back. 

### Host

Applies to All

### Host Details

any host

### Swate version

v1.0.0-alpha.11

**Comment by Freymaurer** [comment]
Fixed this on my end! But ARCitect needs to allow external url for isa-json website first.
