### ISSUE TITLE
[Bug]: term search window too small

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#370]
### What happened?

When searching a term the displayed results cannot be read. 

<img width="527" alt="Screenshot 2024-02-16 at 08 49 04" src="https://github.com/nfdi4plants/Swate/assets/16229676/a0cd16b7-298f-49ec-8325-f8c73af99d6d">

### What did you expect?

Wider display of search results and term definition 

### Host

Applies to All

### Host Details

any

### Swate version

v1.0.0-alpha.11

**Comment by Freymaurer** [comment]
I should propably hide the TAN in this search window, but otherwise i would have to change the width of the column significantly. Which one would you prefer?

**Comment by Freymaurer** [comment]
Set minimum width to 400px, lets see how this feels 👍
