### ISSUE TITLE
[Bug]: term search only yields very few and confusing results 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#371]
### What happened?

For instance, searching for Arabidopsis just yields "Arabidopsis thaliana metabolite" 

<img width="527" alt="Screenshot 2024-02-16 at 08 49 04" src="https://github.com/nfdi4plants/Swate/assets/16229676/c428751e-b9f0-4c92-be82-841601631b28">

### Host

Applies to All

### Host Details

any

### Swate version

v1.0.0-alpha.11

**Comment by Freymaurer** [comment]
Yeah database seems to have an issue, i'll contact Marcel.

**Comment by Freymaurer** [comment]
![image](https://github.com/nfdi4plants/Swate/assets/39732517/e71a5810-dc7c-4573-96ab-7f4796986f5a)

@Zerskk "reset" the database and now all terms should be included again
