### ISSUE TITLE
[Bug]: Quota Exceeded

### ISSUE THREAD

**Issue by caroott** [nfdi4plants/Swate#374]
### What happened?

While working with swate alpha, i encountered the following error after performing multiple subsequent actions:
![image](https://github.com/nfdi4plants/Swate/assets/39764934/8fbd22ab-263d-47dd-a6d5-2043938574f5)
It is possible to continue editing the file, but saving is impossible.

### What did you expect?

Being able to save the file after editin it, even after performing multiple edits.

### Host

Standalone

### Host Details

OS: Windows 11
Browser: Firefox Version 122.0.1 (64 Bit)

### Swate version

Swate Release Version v1.0.0-alpha.12

**Comment by Freymaurer** [comment]
This seems to be an issue with larger assays/studies where, for which we store the states as json in local storage. We are currently investigating ways to decrease json size and should resolve this issue soon

**Comment by Freymaurer** [comment]
Could you pls add the problematic .xlsx file?

**Comment by caroott** [comment]
[isa.study.xlsx](https://github.com/nfdi4plants/Swate/files/14346164/isa.study.xlsx)

**Comment by Freymaurer** [comment]
We have reduced json size significantly. Will close for now, let's see when we run into this the next time
