### ISSUE TITLE
[BUG] SWATE copy functionality errors when trying to copy free text values from one cell to another within term column

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#376]
**OS and framework information (please complete the following information):**
 - OS: Windows 11 
 - Arcitect v: [705ffe4](https://github.com/nfdi4plants/ARCitect/commit/705ffe4ccef1f789a70341f8f074275b8e6fc15a)
 - 
**Describe the bug**
- [x] A clear and concise description of what the bug is
When trying to copy one or more free text values of a term column into another cell of said column i get errors of the following form:Invalid combination of header Characteristic [plasmid] and cells PsbQ_TurboID

- [x] Steps to reproduce
Shown in the screenshots
- [x] Screenshots
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/44786fda-b2d3-4e19-beb0-e01b45eccf5c)

![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/68e5da85-a689-49f7-b4ad-a6ab4183d91c)

![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/aa0af365-df07-4523-98aa-e100d7c2a2e9)

**Comment by Freymaurer** [comment]
Done! will be part of the next release!
