### ISSUE TITLE
[Feature Request] Increase size of the scroll bar of the TableContainer

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#378]
**Is your feature request related to a problem? Please describe.**
I think it would improve usability to increase the vertical size of the scroll bar a little bit.

**Screenshot**

![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/b8690340-0a6a-4c01-8014-c9e2acfdbf4b)

**Comment by Freymaurer** [comment]
Fixed let me know if the new size is better 👍
