### ISSUE TITLE
[Feature Request]SWATE copy functionality should implicitly convert when copying free-text cell values into a term or term or unit cell

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#379]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to copy free text values into a term or unit cell because it is not allowed and errors with errors like this: 
Invalid combination of header `Characteristic [plasmid]` and cells `PsbQ_TurboID`

**Describe the solution you'd like**
The conversion to a term or unit cell should be done implictly as the checkmark besides the input already is sufficient to tell the user about the state of the cell

**Comment by Freymaurer** [comment]
Fixed! But this feature is not trivial. Feel free to poke around in the new version and report any bugs back to me! ✨
