### ISSUE TITLE
[BUG] SWATE Column with unit cells are created with unit as value and display unit when modified

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#380]
**OS and framework information (please complete the following information):**
 Windows 11, ARCitect release 0.0.27

**Describe the bug**
- [x] A clear and concise description of what the bug is
When a column with unit cells is created it contains the unit as a value in the first cell (see screenshot 1). Additionally, when the value is exchanged (see screenshot 2), upon double click the unit value is displayed again (see screenshot 3).

- [x] Steps to reproduce
See screenshots

- [x] Screenshots
<img width="822" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/2b62cb7f-81f2-4c13-9c86-3479ca21b3e6">

<img width="835" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/6c1b82ef-6653-47c2-b8cd-33b863673704">

<img width="835" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/c2b290ae-2182-42f3-af54-794333e1aa8b">

- [x] Expected behavior

initialize without value, when value is modified only show the value, not the unit

**Comment by Freymaurer** [comment]
Fixed! Had neglected the idea that main column only requires search if it is a term cell. This is now correctly handled plus(!) unit cells also allow term search now ✨
