### ISSUE TITLE
[BUG] SWATE Term search does not find exact matches

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#381]
**OS and framework information (please complete the following information):**
 - Windows 11, ARCitect release 0.0.27, Swate Release Version [v1.0.0-alpha.13](https://github.com/nfdi4plants/Swate/releases) 

**Describe the bug**

- [x] A clear and concise description of what the bug is
When creating new columns or adding Term or Unit cells, the search fails to retrieve terms that match exactly, e.g. a search for "column" does not retrieve the term "Column, NCIT:43379" (screenshot 1), a search for "column asd" does (screenshot 2).

- [x] Steps to reproduce
Follow screenshots

- [x] Screenshots

<img width="463" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/50378286-b166-4c24-b73f-c49fa0f87340">

<img width="462" alt="image" src="https://github.com/nfdi4plants/ARCitect/assets/17741807/2d1876ce-c157-4a0b-921e-f2c5fcef5f23">

**Comment by Freymaurer** [comment]
Done! This should perform a lot better in terms of quality. But we should observe if the runtime performance loss is noticable!
