### ISSUE TITLE
[BUG] SWATE copy functionality should allow to copy a single value multiple times at the same time

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#382]
**OS and framework information (please complete the following information):**
Windows 10, Arcitect v. 0.28.0

**Describe the bug**
- [x] A clear and concise description of what the bug is
Trying to copy the state of a single cell using the copy button in the right-click dialogue and then shift clicking multiple target cells and using either "Paste" or "Paste All", I would assume that all shift clicked cells are filled. However, for "Paste" only the first seleced and for "Paste All" only the cell that I opened the context menu on is filled.

- [x] Steps to reproduce
See screenshots
- [x] Screenshots
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/d525541c-d4c2-429f-b80e-b0d609e5fe9d)
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/34dee4ff-c6f3-41d2-a886-c800c33cef2f)
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/acef6c27-e45e-4afd-9db6-08fa038407f1)
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/b9620d7e-7bba-4882-8c8a-16ff5b33d0f0)
![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/433161b5-25e2-48b9-82fe-4bc80efbcb57)

- [x] Expected behavior
Fill all selected cells

**Comment by Freymaurer** [comment]
This is also part of #359

**Comment by Freymaurer** [comment]
Done! Copying a single cell, then selecting multiple cells and using `Paste`, will fill the selected cells with the copied cell.
