### ISSUE TITLE
[Feature Request]: Link terms to TS4TIB service

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/Swate#384]
### Is your feature request related to a problem?

It would be great if all the links displayed next to the terms in Swate would bring users to the TS4TIB service where we set up a DataPLANT collection during the BioHackathon Germany 2023 (https://terminology.tib.eu/ts/ontologies?collection=DataPLANT&and=false&page=1). This can then serve as a singlel entry point for users to research other ontologies in the plant sciences that might be relevant for them and to also explore each ontology. The collection currently includes agro, chebi, efo, ms, ncit, obi, pato, po, to, mod, ro, envo, uo. Links to the TS4TIB service seem to be in this format: "https://terminology.tib.eu/ts/ontologies/<onto>/terms?iri=<iri from the ontology file>&obsoletes=false" . <onto> is the namespace and iri must be the iri we are also currently using (e.g. http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00000050).

### Describe the solution you would like!

It would be great if when we click the link next to the terms in the term search and then be redirected to the term on the TS4TIB service.

### Host

Applies to All

### Host Details

should work for Swate in Excel and in the Browser (Firefox)

**Comment by Freymaurer** [comment]
Can you give me an update on this issue? What ontologies are contained in TIB? What terms can i redicrect to TIB?

**Comment by Hannah-Doerpholz** [comment]
All ontologies are included except:
- ARC
- MIAPPE (our homebrew version)
- CREDiT
- NCBITaxon (both the full one as well as our homebrew one)

Everything else that we currently import through the ext_ontologies.include, as well as our DBPO is in the TIB.
