### ISSUE TITLE
[Bug]: Editing column headers doesn't work

### ISSUE THREAD

**Issue by caroott** [nfdi4plants/Swate#388]
### What happened?

When editing a column by double clicking on the header, editing the text in the then opened text field and pressing enter, the changes done in the text field are not saved.

### What did you expect?

Double klicking on column headers and editing the text should change the text in the column header.

### Host

Standalone

### Host Details

OS: Windows 11
Browser: Firefox Version 122.0.1 (64 Bit)

### Swate version

Swate Release Version v1.0.0-alpha.12

**Comment by Freymaurer** [comment]
Done! This was a stupid mistake (<sub>😞</sub>). Will be live with the next release!
