### ISSUE TITLE
[Feature Request]: increment sample numbers

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#390]
### Is your feature request related to a problem?

Probably not trivial, and probably the goal should not be to rebuild all Excel. 
But it might help to be able to just enter e.g. the name of a first sample "Sample 1" and incrementally fill down the column (Sample 2, Sample 3, ...). 

### Describe the solution you would like!

Just offer two options
- if last character of cell value is a numeric, add +1 (Sample 4, Sample 5, Sample 6, ...)
- if last character is not numeric, add numeric to next cell and increment as above (Sample xy, Sample xy 1, Sample xy 2, ...) 

### Host

Applies to All

### Host Details

any

**Comment by Freymaurer** [comment]
![image](https://github.com/nfdi4plants/Swate/assets/39732517/1d408fee-fae3-4db8-b6a8-75c756b850e1)
