### ISSUE TITLE
[Bug]: widget overlap

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#391]
### What happened?

- widgets are weirdly overlapped by sidebar divider
- last active widget should be in front (currently templates is always in front of building blocks)

<img width="1149" alt="Screenshot 2024-02-28 at 17 33 22" src="https://github.com/nfdi4plants/Swate/assets/16229676/324bd5d8-a8f6-450f-abbe-66183fb061cc">

### Host

Applies to All

### Host Details

Browser

### Swate version

1.0.0-alpha.15

**Comment by Freymaurer** [comment]
I have ... :
*  Removed the strange overlap of the splitwindow bar! <sub>(i was not aware that z-index is always scoped to z-index of parent, in this case the navbar)</sub>
* I have updated the display logic to always show the latest clicked widget in front
* I have updated the widget button function in the navbar to bring the related widget to the front when clicked while opened. So if you have both widgets open, click on the "add" button again to bring it to the front.
* II also added a "clicked-on" handler. so you click on a part of the widget and it jumps to the front.
