### ISSUE TITLE
[Feature Request]: "fill-down" 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#392]
### Is your feature request related to a problem?

"Fill Column" overwrites all column values with the selected one. 

### Describe the solution you would like!

In addition to `Fill Column`, a `Fill Down` function could speed up describing replicate groups. 
Ex.: A Factor: First three samples = "watered", next three samples = "drought-treated". 
I would like to Use `Fill Column` first for "watered". And then go to Cell 4, type "drought-treated" and `Fill Down` from there, etc. 

### Host

Applies to All

### Host Details

any

**Comment by Freymaurer** [comment]
I think this feature is not necessary as it can be handled easily using the `Paste` cell function. Please let me know if this fits your expected behavior! Will close now, feel free to open again 🙂

**Comment by Brilator** [comment]
Ah, I didn't see that `Paste` instead of `Paste All` could do that. Fine
