### ISSUE TITLE
[Feature Request]: allow kbd enter to add rows 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#393]
### Is your feature request related to a problem?

When using the + button to add rows to a table, one has to switch between keyboard and mouse. 
1. type a number
2. click the plus sign

### Describe the solution you would like!

Would be quicker to just hit <kbd>enter<kbd> after entering the number 

### Host

Applies to All

### Host Details

- ARCitect v0.0.28
- Safari v1.0.0-alpha.15

**Comment by Freymaurer** [comment]
Done! ✨ Will be lvie with the next release
