### ISSUE TITLE
[Feature Request]: Add/Edit Freetext cells Modal

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#395]
### Is your feature request related to a problem?

Having to change all fields of a column can not only become cumbersome, but also make machine reading ARCs error prone due to typos.

### Describe the solution you would like!

Have a function to create freetext column values. This should include:

- [x] regex replace
- [x] Fixed basic name
- [x] Option to generate number suffix

### Additional context!

Includes #390, @Brilator @ZimmerD feel free to give additional input 🙂 

### Host

Applies to All

### Host Details

.

**Comment by Freymaurer** [comment]
Done! 

![image](https://github.com/nfdi4plants/Swate/assets/39732517/3ca50800-17c0-445b-9b82-6b7fb1edd207)

**Comment by Brilator** [comment]
I'd suggest to add the following options

- [ ] start suffixes from 1, not 0
- [ ] regex case-insensitive

**Comment by Freymaurer** [comment]
Start suffixes at 1 is no problem. Regex case insensitive is something i'd like to avoid. "Just write better regex", as stupid as i may sound

**Comment by Brilator** [comment]
Fair enough. So we’ll need to teach more regex.   :)

**Comment by Freymaurer** [comment]
![image](https://github.com/nfdi4plants/Swate/assets/39732517/1c058a18-fb97-43f0-9133-3ca594324f1e)

**Comment by Brilator** [comment]
I know basic regex. I meant teaching those people, who we avoid to teach git. ;)

**Comment by Freymaurer** [comment]
Done! Will be live with the next version 🙂
