### ISSUE TITLE
[BUG] Cannot add text to fields in Building Block Dialogue after selecting a cell

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#398]
**OS and framework information (please complete the following information):**
 - OS: [Windows 11]

**Describe the bug**
- [x] A clear and concise description of what the bug is
With the new more excel like cell behaviour in place, after selecting a cell, I cannot type into the Add Building block dialogue, as any typing will automatically modify the last selected cell.
 
- [x] Steps to reproduce
1. Select a cell
2. Open Add Building Block dialogue
3. Select your column type
4. Try to search for teams selecting the text box of the dialogue
5. See that the Cell is modified instead of the text box of the dialogue

- [x] Workaround
Reopen the Sheet, do not select a cell prior to interacting with the building Block dialogue.

**Comment by Freymaurer** [comment]
This was a very interesting issue with React. React seems to use synthetic events. In this case i had mixed React events with native browser events which cannot be stopped from react events. I changed it to use React events only and it should work as intended now 🙂
