### ISSUE TITLE
[Bug]: creating new table does not set correct table index

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#403]
### What happened?

create new table try to add template -> error

When clicking on table on the bottom this resolves the issue

### Host

Applies to All

### Host Details

.

### Swate version

.

**Comment by Freymaurer** [comment]
@SabrinaZander hey, i cannot reproduce this issue. Could you click around and give me a list of steps i can do to reproduce this?

**Comment by SabrinaZander** [comment]
@Freymaurer Hey, I have tried it several times now, but I can no longer reproduce it. Maybe other changes have already solved the problem?

**Comment by Freymaurer** [comment]
As this issue only occured in ARCitect it might have been a symptom of the latest big i fixed. I will close this for now. But please feel free to contact me if it occurs again!
