### ISSUE TITLE
[Feature Request] Add option to look up team definitions in the table

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#407]
**Is your feature request related to a problem? Please describe.**
When using a template a user is given a previously setup table. 
**Describe the solution you'd like**
Add an possibility to look up definitions of terms referenced e.g. in the column header. SImilar to the functionality of the "Get Building Block information" button in previous SWATE versions.

![image](https://github.com/nfdi4plants/ARCitect/assets/17741807/10347a63-ea32-4631-a36d-874dbec7d68c)

**Comment by Freymaurer** [comment]
This will be added minimally with the next release!

![image](https://github.com/user-attachments/assets/d74a91f4-c60e-4009-9d83-6e4322099da8)

![image](https://github.com/user-attachments/assets/d5648533-fcb7-4a31-be29-d5f636afd1c2)
