### ISSUE TITLE
[Feature Request] pre-filter publication status and roles

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#409]
It would be great if ARCitect pre-filter the terms for publication status and roles. Maybe filteringusing parent terms (Ontology) my be possible).
I think publication status only requires "submitted", "published", "in preparation" (like in the older ARCitect versions) and some specific roles like technician, investigator, co-investigator, doctoral researcher etc. were fine. Otherwise it is confusing and not really logical.

**Comment by Freymaurer** [comment]
Hello! Yes this is something i have definetly planned! But i need the help of the ontology team to accomplish this.

Similiar to this here: https://github.com/nfdi4plants/nfdi4plants_ontology/issues/85

I would need to know a parent term then i could improve search to highlight child terms. But i simply do not know which terms i should set here.

**Comment by Freymaurer** [comment]
@SabrinaZander i will start implementing this as soon as i get more information about what term to use 🙂

**Comment by Freymaurer** [comment]
@StellaEggels maybe you can give me more information on this? 😅

**Comment by StellaEggels** [comment]
For publication status you can use the EFO term "publication status" (EFO:0001742) with all its child terms as options: 
![grafik](https://github.com/nfdi4plants/Swate/assets/147173792/024d07f0-a745-4e62-84ab-394c66262674)

For role I would suggest the AGRO term "person role within the experiment" (AGRO:00000378) with all its child terms as options:

![grafik](https://github.com/nfdi4plants/Swate/assets/147173792/8b8a3670-71ca-4c58-af0d-9bb9e53caf27)

**Comment by Freymaurer** [comment]
@StellaEggels Thanks a lot! Awesome!

**Comment by Freymaurer** [comment]
@StellaEggels 

> For role I would suggest the AGRO term "person role within the experiment" (AGRO:00000378) with all its child terms as options:

This is not included in SwateDB?

![image](https://github.com/nfdi4plants/Swate/assets/39732517/40a51961-f3d2-4e2a-8343-f03c9a104401)

**Comment by StellaEggels** [comment]
I added it now
