### ISSUE TITLE
[Feature Request]: Create ISA table from existing non-ISA-table (xlsx, csv, ..)

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#412]
### Is your feature request related to a problem?

Some tables already existing in the lab (e.g. sample lists) are close to ISA format (somewhat tidy data frames). 
However, to convert them into ISA is annoying with the current options:
1. Build table completely new using e.g. Swate
2. Build only table headers and copy paste column by column
3. Add building block add-ons (unit, TSR, TAN) and ISA-conform headers to existing table 

### Describe the solution you would like!

a) Quick(er) solution to make 2. easier: support copy / paste across multiple columns and rows (without ontology info) from Excel to Swate
b) more complex: Import GUI to convert existing headers to selectable ISA building block types 

### Host

Applies to All

### Host Details

all

**Comment by Freymaurer** [comment]
> a) Quick(er) solution to make 2. easier: support copy / paste across multiple columns and rows (without ontology info) from Excel to Swate

I do not see what logic we could use to know when a new column starts. Excel separates all columns when copied to clipboard with a tab. I use the same logic to enable copy-pasting between Swate tables and Swate and Excel. But that means, that i split by tab and then put the resulting strings into main column, (unit) (tsr and tan). No idea how this could be updated to know the difference between reference columns and a new column

 > b) more complex: Import GUI to convert existing headers to selectable ISA building block types

More feasible, will have a look. You could also write the import logic with ARCtrl and submit it to me and i build the UI on top. This would speep up the process and priority of the issue.

**Comment by Freymaurer** [comment]
@Brilator Can you give me some examples how these non-swate tables look like?

**Comment by Brilator** [comment]
[00_SampleInfo.xlsx](https://github.com/user-attachments/files/15886508/00_SampleInfo.xlsx)

**Comment by Freymaurer** [comment]
I will close this issue, for now. It seems out of scope. Instead i think excel functionality should be improved to better handle copy-pasting. Feel free to open new issues with this direction 🙂
