### ISSUE TITLE
[Feature Request]: support protocol import

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#413]
### Is your feature request related to a problem?

The Excel plug-in allowed to import a filled out process / protocol as .json

### Describe the solution you would like!

Would help to offer this feature again in swate alpha / ARCitect 

### Host

Standalone

### Host Details

Standalone and ARCitect

**Comment by Freymaurer** [comment]
@Brilator What information should be imported? Full assay? Just a single table?

**Comment by Freymaurer** [comment]
Make it choosable what to import!

**Comment by Freymaurer** [comment]
Not finished, but here is a preview of the current design:



![Image](https://github.com/nfdi4plants/Swate/assets/39732517/041c509c-4227-469e-8916-71da9eec7420)

**Comment by Freymaurer** [comment]
@Brilator Have a look and tell me if that is the correct direction 🙂

**Comment by Brilator** [comment]
(Direction) looks very good

- "Import type" options are exclusive? Either column headers _or_ column headers + predefined units _or_ column headers + units + values. If so, I would rearrange accordingly. 
- "Metadata" might be confusing. Needs to be clearer what metadata is meant here (it's the top-level ISA metadata right? So study/ assay or template info with person records etc., i.e. not biological / experimental metadata) 
- Multiple Template Tables (Table 1, Table 2) would origin from an isa.assay.xlsx / isa.study.xlsx with multiple sheets "Table 1"? I really like the flexible options (import, append, no import)
  - What's behind the dropdown? 
  - I think "Template" is misleading and should be something like "ISA table"

**Comment by Freymaurer** [comment]
> "Import type" options are exclusive? Either column headers or column headers + predefined units or column headers + units + values. If so, I would rearrange accordingly.

Yes Options, are exclusive and exactly as you think they are. Will rearrange!

> "Metadata" might be confusing. Needs to be clearer what metadata is meant here (it's the top-level ISA metadata right? So study/ assay or template info with person records etc., i.e. not biological / experimental metadata)

Exactly! How should i rename it? Because ISA seems not directly correct, and top-level not very intuitive.

> Multiple Template Tables (Table 1, Table 2) would origin from an isa.assay.xlsx / isa.study.xlsx with multiple sheets "Table 1"? I really like the flexible options (import, append, no import)

Yes!

> I think "Template" is misleading and should be something like "ISA table"

`Template Table 1` is the name i gave the table, so it will be whatever the table was called by the protocol creator.

> What's behind the dropdown?

A scrollable table preview of the protocol table:

![image](https://github.com/nfdi4plants/Swate/assets/39732517/4e485d40-13bb-4e0a-bd30-ec6ed1f33dfd)

Thinking about it now, i should propably already show correct format and not inverse column and row 😞

**Comment by Brilator** [comment]
> Exactly! How should i rename it? Because ISA seems not directly correct, and top-level not very intuitive.

Tricky. Description / Details / Information / Meta information / Registration / Registry metadata / about the table to be imported. 

Maybe more importantly, I'd suggest to move that modal down to bottom and have the box unchecked by default. 

> A scrollable table preview of the protocol table:

Nice. 

> Thinking about it now, i should propably already show correct format and not inverse column and row 

Yes

**Comment by Freymaurer** [comment]
>Tricky. Description / Details / Information / Meta information / Registration / Registry metadata / about the table to be imported.
>
>Maybe more importantly, I'd suggest to move that modal down to bottom and have the box unchecked by default.

I am now checking which file was imported and add the filetype in front of the Metadata:

![image](https://github.com/nfdi4plants/Swate/assets/39732517/5cb514fd-2997-46a1-b3b5-356254bdd90f)

And currently everything is unchecked by default 😅 

> >Thinking about it now, i should propably already show correct format and not inverse column and row
>
>Yes

Done!

**Comment by Freymaurer** [comment]
I finally finished the logic. As it is a rather complex logic, feel free to open an issue if it feels off!

Will be live with the next release!
