### ISSUE TITLE
[Feature Request]: Make template search more specific

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/Swate#414]
### Is your feature request related to a problem?

When you search for a template by its name, too many templates with loosely similar or even not obviously similar names are shown that make it harder to find the template you are looking for.

![issue_swatetemplatesuche2](https://github.com/nfdi4plants/Swate/assets/147173792/c4d0108c-8f00-4a9b-8847-2283cd543e85)

### Describe the solution you would like!

Only suggest templates that closely fit the terms you are looking for, when using the "search by template name".

### Host

Standalone

### Host Details

Firefox

**Comment by Freymaurer** [comment]
I looked into it and i had and there was a bug, that the actual sorting was not applied. Only a very slight filter for completly different names. I made the filter a bit more strict and applied the sorting correctly:



![Image](https://github.com/nfdi4plants/Swate/assets/39732517/3854ecc1-3f1e-4de1-a9d4-b069105f1b36)

**Comment by Freymaurer** [comment]
This will be part of the next release!
