### ISSUE TITLE
[Bug]: Building blocks added with template although they already exist

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#415]
### What happened?

- Create a new table
- add e.g. "organism" as characteristic
- add a template that contains the same "organism" (same ontology term) 
- the building block is now duplicated   

### What did you expect?

add only non-existing building blocks 

### Host

Standalone

### Host Details

ARCitect

### Swate version

v1.0.0-beta.03 Host ARCitect

**Comment by Freymaurer** [comment]
Hey! Can you give me the name of the template you used?

**Comment by Brilator** [comment]
Plant Source Material

**Comment by StellaEggels** [comment]
It happened again in the training today with the same example. For 3 out of 5 people, organism was added a second time, for the other 2 only the missing building blocks were added. All used the same ARCitect version and the difference wasn't between Mac and Windows.

**Comment by Freymaurer** [comment]
Most likely fixed with: https://github.com/nfdi4plants/Swate/issues/436 !

Will close for now. Should this occur again, feel free to reopen!
