### ISSUE TITLE
[Bug]: values over-written when adding template

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#416]
### What happened?

- Input [Source Name] column already holds values (e.g. sample names)
- add a template with Input [Source Name]
- overwrites / clears values

### Host

ARCitect

### Host Details

ARCitect

### Swate version

Swate Release Version v1.0.0-beta.03 Host ARCitect

**Comment by Freymaurer** [comment]
related to #410

**Comment by Freymaurer** [comment]
Fixed! This will be part of the next release!
