### ISSUE TITLE
Delete Building Block

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#418]
### Is your feature request related to a problem?

I am missing the "delete Building block" feature in case i wrote a wrong building block

### Describe the solution you would like!

add a "delete building block" button,
also i had problems adding a unit to an existing building block, is this possible?
with delete building block, i could add a new one, delete the old one...

### Host

Applies to All

### Host Details

Arcitect Swate 1.0.0 beta.03

**Comment by Freymaurer** [comment]
This functionality exists:

You can use:

`Delete Column`, to remove a building block.

`As Unit Cell` to transform a term cell to a unit cell

![image](https://github.com/nfdi4plants/Swate/assets/39732517/d11481de-b4ef-4508-b9b1-10474965dfc4)
