### ISSUE TITLE
[Bug]: Unit is only displayed in first row

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#419]
### What happened?

When you add building blocks with a unit the unit is only displayed in the first row. 
In all other rows the Unit/TSR/TAN building block is empty.

![Screenshot 2024-05-13 131210](https://github.com/nfdi4plants/Swate/assets/127506066/5b168a8f-e496-4156-a363-da21a43a7432)

### What did you expect?

Unit information should be added in all rows. 

### Host

ARCitect

### Host Details

ARCitect v.0.0.31

### Swate version

 v1.0.0-beta.03

**Comment by Freymaurer** [comment]
What was your workflow?

Added building block with unit. Then added rows? Or were there already 3 rows and you added a building block afterwards?

**Comment by SabrinaZander** [comment]
I first added building blocks with unit and then added rows. But I tried also the other way around and the problem is still the same.

**Comment by ZimmerD** [comment]
Can confirm this behaviour on my machine, windows 11, 23H2

**Comment by Freymaurer** [comment]
I am a bit conflicted about this issue, as the behavior exactly mimics the behavior of adding a building block with a term:


![Image](https://github.com/nfdi4plants/Swate/assets/39732517/8645c574-0b06-4dce-87cc-6489e9d34eaf)

Which will add the term exactly in row 1. I am a big fan of consistency and wanted to ask:

1. Should i also fill the full collumn for terms?
2. Should i only fill units for the full column?

@ZimmerD @SabrinaZander

**Comment by SabrinaZander** [comment]
In my opinion, only units should be filled for the entire column. Because I think it is more likely that the terms will be different in different rows ( see example). 
If you want to have the same term in the whole column you can easiely use the fill column button. With units it is not that easy. Only when you do this at step 1 and you don't have any numbers in the colums yet. Otherwise you will have the same number with a unit in all columns.  

Hope you can understand what I mean :-) 


![image](https://github.com/nfdi4plants/Swate/assets/127506066/dd0ab012-6715-4e00-bb12-b64fac19f4c9)

**Comment by Freymaurer** [comment]
I had some discussions about this issue and the following will be implemented:

The Add Building block logic will always fill all available rows with the body term! I think this is the best solution and fits user expectations best.

**Comment by Freymaurer** [comment]
Done! This will be part of the next release!
