### ISSUE TITLE
cannot add fasta file picking 

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#420]
### What happened?

filling out an assay

trying to reference an fasta data file using file picker, file located in the corresponding study/resources

error occuring (see snippet)

tried to rename the fasta, tried new column (Parameter or Component etc. , new Ontology entry) no success

![grafik](https://github.com/nfdi4plants/Swate/assets/97098130/339deefb-3e2b-4211-95e0-61245b7c0fe5)

![grafik](https://github.com/nfdi4plants/Swate/assets/97098130/dabbc9ab-7039-474f-9d7d-24b1386c10d3)

### What did you expect?

link to fasta file used

### Host

ARCitect

### Host Details

Arcitect 0.0.31
swate 1.0.0-beta.03

### Swate version

1.0.0-beta.03

**Comment by Freymaurer** [comment]
I think i know why this happends. File picker was expected to be used for Input/Output columns. Not for Term columns. I will discuss this issue with @HLWeil and post an update soon

**Comment by frsommer** [comment]
perfect,
i was told that rescources are the right place to drop the fasta

**Comment by Freymaurer** [comment]
@HLWeil

**Comment by Freymaurer** [comment]
I just talked to @HLWeil and he deems this sensible 👍

**Comment by Freymaurer** [comment]
Done! This will be part of the next release!
