### ISSUE TITLE
Need Ontology terms for PASEF methods

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#421]
### Is your feature request related to a problem?

trying to describe "mass spectrometry acquisition aspect" or similar.

need description for PASEF methods:
diaPASEF (existing as MS:1003225)
ddaPASEF
prmPASEF

are a Bruker terms

### Describe the solution you would like!

need these terms

### Host

ARCitect

### Host Details

ARCHItect 0.0.31
swate 1.0.0-beta03

**Comment by StellaEggels** [comment]
Thank you for your suggestions. diaPASEF (PRIDE:0000650), prm-PASEF (DPBO:0000097) and dda-PASEF (DPBO:0000098) have been added to our ontology and are now available in ARCitect and Swate.

**Comment by Freymaurer** [comment]
So my guess is this is solved by now and i can close the issue. Big thanks to you @StellaEggels 🥇
