### ISSUE TITLE
[Feature Request]: Show example terms for templates

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/Swate#423]
### Is your feature request related to a problem?

Sometimes it can be difficult to interpret the column headers of templates and know what kind of terms the columns should be filled with, especially for repository templates.

### Describe the solution you would like!

It would be helpful to have one row of example terms shown for each template (e.g. in grey, will be overwritten as soon as cell is being filled in) to make it clear to users what kind of terms would be expected and make the meaning of the column header more clear. Could also be an option to select “show example terms" instead of showing them by default. For this, example values still have to be added to the template xlsx files.

### Host

Applies to All

### Host Details

all

**Comment by Freymaurer** [comment]
Tracked in https://github.com/nfdi4plants/Swate/issues/499 will close here
