### ISSUE TITLE
[Feature Request]: Enable adding multiple templates at once

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/Swate#424]
### Is your feature request related to a problem?

Combining multiple templates in one annotation table can be quite tedious at the moment.

### Describe the solution you would like!

It would be great if you could add multiple templates at once, especially if we focus on adding smaller templates that can be combined into one assay/study table (e.g. plant source material and plant growth conditions and plant sampling). For this, expanding/unexpanding the template preview more easily (without losing the position in the template list) and an option for selecting which templates to add at once would be needed. Suggestion by @Brilator .

### Host

Applies to All

### Host Details

all

**Comment by Brilator** [comment]
<img width="1282" alt="Screenshot 2024-05-16 at 09 14 23" src="https://github.com/nfdi4plants/Swate/assets/16229676/dd9b9e74-5fc7-4ac9-8d0a-cd94c42bae76">

**Comment by Freymaurer** [comment]
Tracked in https://github.com/nfdi4plants/Swate/issues/499 will close here
