### ISSUE TITLE
[Feature Request]: Option to select which building blocks of a template to add

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/Swate#425]
### Is your feature request related to a problem?

If you only want to add a couple of building blocks from a template, adding all building blocks from the template first and then deleting the ones you don't want can be a bit annoying.

### Describe the solution you would like!

An option to select which building blocks of a template to add to your annotation table, instead of first adding all and then having to delete building blocks. 

### Host

Applies to All

### Host Details

all

**Comment by Freymaurer** [comment]
Tracked in https://github.com/nfdi4plants/Swate/issues/499 will close here
