### ISSUE TITLE
[Bug]: "Clear" function also clear units 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#426]
### What happened?

I wanted to change some numbers in a column in an already filled table. I used the "clear" function to delete the numbers. After adding new numbers the units disappeared.

![Screenshot 2024-05-16 091156](https://github.com/nfdi4plants/Swate/assets/127506066/1edc5b62-6a88-498d-b547-a75592e178dd)

![Screenshot 2024-05-16 091233](https://github.com/nfdi4plants/Swate/assets/127506066/bd16b957-4772-4c93-8b3f-517c2ea50212)

### What did you expect?

"Clear" function, should not clear units, if they are specified in the building block.

### Host

ARCitect

### Host Details

Windows 11
ARCitect v0.0.31

### Swate version

 v1.0.0-beta.03

**Comment by Freymaurer** [comment]
This is currently intended behavior. It is intended to clear a full cell, plus the relevant reference cells. 

What do you suggest, changing the name to clear up misunderstanding, or adding an additional function?

**Comment by SabrinaZander** [comment]
I'm not sure about that. It would be great to have a button to only delete numbers, but not the unit. Otherwise it's annoying to change sheets that have already been filled out.
An example use case would be that a user copies metadata sheets from one assay to another because there are only small changes in the experiment and it's too much work for the user to create a completely new Swate table.

**Comment by Freymaurer** [comment]
I am trying to narrow down the use case. In your scenario would it also be feasible to update one cell and propagate it to all other cells?



![Image](https://github.com/nfdi4plants/Swate/assets/39732517/fb7cc604-6713-4b81-9337-d76e2e1de8e5)

**Comment by SabrinaZander** [comment]
This depends on the experiment. I think it would not be feasible for all experiments. If you change a parameter for e.g. temperature for all samples, it works fine. But sometimes you need individueal numbers per sample. So you have to change every entry individually e.g. 
![Screenshot 2024-06-19 091626](https://github.com/nfdi4plants/Swate/assets/127506066/6f4b33a9-3f8b-43ff-9395-38a7f96a8cd2)

**Comment by SabrinaZander** [comment]
I think I may be missunderstood the clear button. In my example above, you have to change the numbers anyway. So changing the number isn't more difficult than entering a new number. 
Maybe we can close the issue for now. But what was the purpose of the clear button? I haven't understood that yet.

**Comment by Freymaurer** [comment]
The purpose of the clear button is to remove the information from the main and reference cells of one building block 👍 Will close for now, feel free to reopen 🙂
