### ISSUE TITLE
[BUG] Ontology Source References

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#428]
I don't see the need for the "Ontology Source References" field in the Investigation Metadata sheet. Maybe it can be deleted in ARCitect or at least placed at the end of the Metadata sheet. Since it doesn't autofill, it just confuses the user.  

![Screenshot 2024-03-06 120054_1](https://github.com/nfdi4plants/ARCitect/assets/127506066/e701b73d-f5f8-4a98-84b5-ee6e5add79e8)

**Comment by Freymaurer** [comment]
Placed on the end, will close for now. Might be good to revisit in the future!
