### ISSUE TITLE
[Feature Request] Changing existing column descriptions

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/Swate#430]
We received an anonymous feature request on April 18th via the DataPLANT Helpdesk.

"When annotating assays/studies in ARCitect, I repeatedly create several columns and fill them out. Later during the process I realize, a different column type/description is more adequate and want then to change the coulmn type/descroption without changing the data in that column. I think this is not possible so far. I realize I can make a new column, copy the data and delete the old one but thats cumbersome. It would be handy to simple change the type/description of the existing one."

**Comment by Hannah-Doerpholz** [comment]
I just came across the same issue that you can't change the column type or description later on. Maybe it would be nice to add these two options to the column dropdown menu where you can also change from term to unit cell and so on.

**Comment by Freymaurer** [comment]
Not entirely sure what "description" refers to, but i will add the option to change column type 👍

**Comment by Freymaurer** [comment]
Done, will be part of the next release! Can be found in the context menu
