### ISSUE TITLE
Add a version information endpoint to the application

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#44]
Both the API and the client application should contain version info. I imagine it like this:

- [x] the major API version can be shown in the backend via routing: `/IAnnotatorAPI/v1/YOUR/ROUTE/HERE`
- [x] The client should have either an info tab or footer () that displays the version of the deployed application (e.g. `0.1-beta` atm), and this should be populated via a call to the backend. 
- [x] Bonus points if this gets automated via FAKE release notes versioning

**Comment by Freymaurer** [comment]
I am currently thinking about how we can implement this without creating a lot more overhead for us during development. And i would really like to discuss the following with you:

I changed Route.builder to:
![grafik](https://user-images.githubusercontent.com/39732517/98370349-bb72ff80-203a-11eb-89c6-fe57aa587d5b.png)
Allowing us to easily create paths with the versioning integrated. This is then followed up in Server.fs by:

![grafik](https://user-images.githubusercontent.com/39732517/98371396-67691a80-203c-11eb-9f52-2f4675474ae1.png)

This is a big one, so let me explain. All Fable remoting APIs are now forwarded to `mainApiController`, which has one forward for each fable remoting API we use (This will be important as soon as we have any form of authentication). Each forward can use any integer as version for the api so we have to test for released Api versions. In this example we obviously only have version 1 so we respon with a error message should someone try to access any version except `1`. When we release new API version we can just add the released version like `|1 |2 -> api stuff` or even have a pattern matching function that we can use for all API to improve scaleability. Anyhow, the version is then parsed to the routebuilder and the api itself where we have multiple options to manage versioning, but i think i would approve of the following way the most:

![grafik](https://user-images.githubusercontent.com/39732517/98372046-713f4d80-203d-11eb-8d79-d437082cab34.png)

This allows us to easily change only the functions that changed with the version with minimum effort. Let me hear what you think about it.

**Comment by kMutagene** [comment]
Looking good so far, documentation may look like it fails, but its actually hosted under the same /v1 path. Maybe rename the webapp function to something more expressive like generateAPIWithVersion.

**Comment by kMutagene** [comment]
After further investigation on how Fable.Remoting builds the routes, using /vXYZ is not the wa to go, rather a new API interface like this: IAnnotatorAPIv1 [] ; IAnnotatorAPIv2 {}

**Comment by Freymaurer** [comment]
@kMutagene regarding the following:

> Bonus points if this gets automated via FAKE release notes versioning

Is this what you meant?

Build.fs
![grafik](https://user-images.githubusercontent.com/39732517/99555556-bb6eea00-29c0-11eb-9f66-b949680c3354.png)

Server/Version.fs
![grafik](https://user-images.githubusercontent.com/39732517/99555469-a7c38380-29c0-11eb-9595-b03f9076b695.png)

The Information is parsed from RELEASE_NOTES.md

**Comment by Freymaurer** [comment]
I hope this will get me all the bonus points. i will write an extensive part about this in the README.md soon, but for now:

- `dotnet fake build -t release` will check if README.md exists and if it does it compares the current commits to the last commit used for the release notes. It will then add the latest commit messaged to the latest release notes. 
This is the default behavior and will not increase the number of the SemVersioning.
- The tags `semver:patch`, `semver:minor`, `semver:major` as in `dotnet fake build -t release semver:patch` will add a new release with either increased major, minor or patch number.
- The function will also do some light key word searching do determine for obvious commit messages if it belongs to the Additions, Deletions or Bugfixes category.
- At the moment FAKE has an error in parsing the SemVer of the release notes (https://github.com/fsharp/FAKE/issues/2557) so the lates commit for each release is currently saved in "Additions", this will be removed as soon as the SemRev.MetaData is fixed.
- After RELEASE_NOTES.md is updated, the function will update Version.fs with the latest release SemRev and this is then used for the client app version, etc.

**Comment by kMutagene** [comment]
Thats pretty cool @Freymaurer ! To get the last bonus point, automate the GitHub release draft via FAKE aswell, so you have a release draft with the correct version tag etc. when you execute the `release` target. But don't get me wrong, thats already good stuff 💯

**Comment by Freymaurer** [comment]
Okay, i added an extra fake target `dotnet fake build -t githubdraft`, which will parse the latest release in RELEASE_NOTES.md and create a draft from these notes. It will upload all files in .assets as asset and add a predefined text (in build.fs) after the latest release notes.

Example:
![grafik](https://user-images.githubusercontent.com/39732517/99882446-d6d83000-2c20-11eb-850b-283bddade36a.png)
