### ISSUE TITLE
[Bug]: Unit is displayed twice when you enter a unit afterwards

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#440]
### What happened?

When you chance a Term cell into a Unit cell and type in a Unit, the unit is displyed twice. 
This also happends when you search for a Unit in an empty unit cell.

Steps to reproduce: 
1. Change a Term cell to a Unit cell ( or use a "free" unit cell)
2. search for a Unit in the Unit cell and select it
3. unit will be displayed twice ( I think 1. what you type in to search for the unit 2. the unit you select)
4. also if there was any entry in the cell before, it is overwritten by the unit

Before 
![Screenshot 2024-06-24 094842](https://github.com/nfdi4plants/Swate/assets/127506066/8e0c4fcb-15dd-451d-8411-29cfd6a57f2c)
Search for unit
![Screenshot 2024-06-24 100537](https://github.com/nfdi4plants/Swate/assets/127506066/cec4c829-9021-4572-bb8e-a3a21facd69f)
Select Unit 
![Screenshot 2024-06-24 100544](https://github.com/nfdi4plants/Swate/assets/127506066/8806921c-1d13-4107-aa61-ea92986e9794)

### What did you expect?

Selected unit should be displayed with the number ( in the example 20 microliter) 

### Host

ARCitect

### Host Details

Windows 11
ARCitect v.0.0.35

### Swate version

v1.0.0-beta.03

**Comment by Freymaurer** [comment]
I will look into this, and see if the changes already made fixed this issue or if it still needs to be resolved!

**Comment by Freymaurer** [comment]
I found the underlying issue! The main cell was not correctly updating a value but instead the unit name. This should be resolved with the next release!
