### ISSUE TITLE
[Bug]: SWATE service is down

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#444]
### What happened?

The standalone service at https://swate-alpha.nfdi4plants.org/ and the ARCitect plugin is not available

### Host

Applies to All

### Host Details

Windows 11

### Swate version

current

**Comment by Freymaurer** [comment]
Yes this error was already reported and will hopefully be fixed soon 🙂

**Comment by Freymaurer** [comment]
This error is resolved now!
