### ISSUE TITLE
[Excel] Add Building block

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#446]
- [x] #470
- [x] #471
- [x] #472
- [x] #473

**Comment by Etschbeijer** [comment]
Create annotation table ->
* Building blocks adapt existing annotation table
* Only one input and output and everything under more per table

**Comment by Etschbeijer** [comment]
Potential process:
Read current annotation table in excel, adapt it with building blocks and write it anew

**Comment by Etschbeijer** [comment]
Helper function -> toNumberFormat & ofNumberFormat in Shared for help
