### ISSUE TITLE
[Excel] Create new table + keep prev output

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#448]

**Comment by Etschbeijer** [comment]
@Freymaurer More information is required.

**Comment by Freymaurer** [comment]
Currently Swate allows the user to copy the output of the previous table to the input of the new table. This is triggered on "Add new table" buttons by pressing the `Ctrl` key (or on MAC the `Meta` key, this might be a missing feature in the old excel logic).

**Comment by Etschbeijer** [comment]
When generating a new table in a new worksheet, while holding strg (windows), the values in output are transferred as input into the newly generate table.
The output values are transferred from the previous worksheet.

**Comment by Etschbeijer** [comment]
1st table

![Image](https://github.com/nfdi4plants/Swate/assets/30893791/0e4dd306-749c-437d-891e-266cbb91145a)


2nd table
![Image](https://github.com/nfdi4plants/Swate/assets/30893791/895583b8-ef8e-4f04-87da-2c7ebde8283e)
