### ISSUE TITLE
Change history tab to info tab

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#46]
This tab should contain:
- [x] a high level description of the tool's functionality
- [x] links to both feature and API docs
- [x] direct link to GitHub issues to discuss and report bugs
- [x] social links to get in touch (add the bird icon and stuff)
- [x] the log history should move to a auto-collapsed dropdown below all of this, associated with a hint that this is fo dev/bug report purposes.

**Comment by Freymaurer** [comment]
> the log history should move to a auto-collapsed dropdown below all of this, associated with a hint that this is fo dev/bug report purposes.

For now i added this to the navbar burger element.
