### ISSUE TITLE
[Bug]: Template creation with Output Data can not be saved/exported

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#462]
### Contact Details

sabrina.zander@hhu.de

### What happened?

When you create a new Template with Swate standalone and you use Data as Output, the template cannot be saved/exported. 
You get an error: Not a Data cell
![Screenshot 2024-07-03 134728](https://github.com/nfdi4plants/Swate/assets/127506066/ae028eee-e119-4576-ae50-6ebd100e1afd)

### What did you expect?

Template should be exported as .xlsx

### Host

Standalone

### Host Details

Windows 11

### Swate version

is not shown anymore? I assume v.1.00 beta 04

**Comment by Freymaurer** [comment]
I will look into this, the current issue #438 might solve this!

**Comment by Freymaurer** [comment]
@HLWeil i though data output could handle freetext (what should be currently) and data cells?

**Comment by Hannah-Doerpholz** [comment]
I'm not sure if this relates or if I should open a new issue, but today when I tried to annotate my own data (not using a template), when I added the Output [Data] column and then tried to save my ARC (without filling the cells in that column) I could not save the ARC anymore. I get stuck with the loader overlay. If you think this is a different issue I'll open a new one.

**Comment by Freymaurer** [comment]
Fixed, this will be live with the next release
