### ISSUE TITLE
Add documentation for featureset and API

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#47]
Feature documentation should be linked via the info tab (see #46) and describe the functionality that is done in the frontend, e.g. the annotation functionality and term search. It is up for discussion whether to host this on gh-pages, the application itself, or use a wiki for that. API docs can be auto generated but must be populated via examples.

- [x]  Api documentation

- [ ] Feature documentation

**Comment by Freymaurer** [comment]
I added api documentation, but for currently unknown reasons the examples for `getTermsForAdvancedSearch` are not showing.

**Comment by Freymaurer** [comment]
After some testing i am pretty sure, that Fable.Remoting has a problem with `System.DateTime`, but i contacted the developer to get this solved.
