### ISSUE TITLE
[Bug]: Output [Data] can't be saved

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/Swate#481]
### What happened?

I checked today if the issue with saving ARCs that have an "Ouput [Data]" column is still there. I could save the ARC with a Output [Data] column but only as long as I didn't add any rows to my ARC, just the column headers. The ARCitect get's stuck wile trying to save the ARC. In the picture you can see what I tried to save. First, I added the input and output column headers and saved the ARC (successfully). Then, I added one row and put in some dummy values, clicked "save ARC" and got stuck in the saving screen.

![grafik](https://github.com/user-attachments/assets/8089a718-e19c-46b1-8f8e-4b2a95f4743a)

### Host

ARCitect

### Host Details

ARCitect version 0.0.37
Ubuntu 22.04 

### Swate version

1.0.0-beta.05

**Comment by Freymaurer** [comment]
This is to be expected, please update to ARCitect v0.0.38 🙂 Feel free to reopen if this should not resolve your issue!
