### ISSUE TITLE
[Feature Request]: DataMap header terms

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#483]
### Is your feature request related to a problem?

The new datamap feature contains three term like headers:

![image](https://github.com/user-attachments/assets/f538549b-b260-4005-9c19-3d3c6af152f4)

* Explication
* Unit
* Object Type

Currently these are added without identifier, therefore no parent-child search triggers and it simply looks like mistake

### Describe the solution you would like!

These terms should also be referenced using identifier, similiar to featured column Protocol Type

Which terms should we use for this? This will also support parent-child search for these columns.

Maybe you can tell me which terms would fit best @StellaEggels .

### Additional context!

https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#datamap-table-sheets

### Host

Applies to All

### Host Details

.

**Comment by StellaEggels** [comment]
For unit you can for sure use the unit ontology (UO:0000000), for Object type I think data type (NCIT:C42645) will fit. Explication isn't clear to me, maybe Data item (SIO:000069) or data file description (NGBO:6000418), but I am not sure if that is what is asked here.

**Comment by Freymaurer** [comment]
@HLWeil can you verify?

**Comment by HLWeil** [comment]
"Unit" and "Data Type" proposed by @StellaEggels fit well. 
Not sure if we should costrain the rave of Explication though. It's kind of a wildcard for any term.

**Comment by Freymaurer** [comment]
Thanks, will start implementing then!

**Comment by HLWeil** [comment]
On another note: 
1. Is it possible to remove the "Parameter" part of the headers
1. Is it possible to remove the units?

**Comment by Freymaurer** [comment]
> Is it possible to remove the "Parameter" part of the headers?

Yes we would need to implement these as FeaturedColumns in ARCtrl (to be factually correct) or i can hardcode something in Swate

> Is it possible to remove the units?

This is just a ui thing. it is greyed out, they do not have units. Maybe this can be improved in the future. This behavior is consistent across all Swate tables.

**Comment by Freymaurer** [comment]
Just talked to @HLWeil about this and mabye its a good idea to create a new term `explication` without any child terms. Therefore we would have an ontologized header term without narrowing down the child search. What do you think @StellaEggels ?

**Comment by StellaEggels** [comment]
Sounds good, if you can provide a definition I will add it to DPBO.

**Comment by Freymaurer** [comment]
@HLWeil ?

**Comment by HLWeil** [comment]
I would go from here:

https://ontobee.org/ontology/NCIT?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C86073

### Class: Explanation
- Term IRI: http://purl.obolibrary.org/obo/NCIT_C86073
- Definition: A set of statements describing a group of facts that clarifies the cause, context and/or consequence of those facts.


and adjust to:

### Class: Explication
- Term IRI: ...
- Definition: A word, term or short statement that clarifies the cause, context and/or consequence of another entity.

**Comment by StellaEggels** [comment]
added (DPBO:0000111)

**Comment by Freymaurer** [comment]
Thanks everyone for contributing! @StellaEggels @HLWeil
