### ISSUE TITLE
[Feature Request]: remove / hide TAN and TSR from top-level metadata

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#487]
### Contact Details

issue

### Is your feature request related to a problem?

- ontology info might confuse users
- info is hidden in table view (when filling building blocks)
![Screenshot 2024-07-16 at 15 05 14](https://github.com/user-attachments/assets/0040cd70-7070-4a97-b840-78b64f7170b5)

### Describe the solution you would like!

I'd suggest to do that similarly for top-level metadata: hide TSR and TAN fields

### Host

Applies to All

### Host Details

all

**Comment by Freymaurer** [comment]
Done! Hidden by default now!
