### ISSUE TITLE
[Feature Request] Rename table to template name on import

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/Swate#489]
**Is your feature request related to a problem? Please describe.**
I often load a template, then manually rename the table from the default title "NewTableX" to the name of the template.

**Describe the solution you'd like**
It would be convenient if it automatically renamed the table to the template name when loading a table from template. 

**Describe alternatives you've considered**
Manually renaming is not a big deal, but I just find myself using the template name as table title most of the time, so it feels like it could be automated and save people some time.

**Comment by shiltemann** [comment]
Fair enough, perhaps only if the table name is still at the default? Offering a checkbox makes it the most explicit in terms of expectations, agreed.

Or perhaps instead of having it be a 2 step process of adding a new table followed by loading a template, make it a single action, "add table from template"?

**Comment by Freymaurer** [comment]
Yeah the template add logic will soon receive a rework, partially based on how protocol import from files looks like:

![image](https://github.com/user-attachments/assets/39c127fa-84ae-483c-8c79-f124fea6e107)
