### ISSUE TITLE
[BUG] Improve template search functionality

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/Swate#490]
When searching templates in ARCitect, the search results are sometimes suboptimal.

**OS and framework information:**
 - OS: Ubuntu 22.04
 - ARCitect version: v0.0.40

**Describe the bug**
Example:
1. Searching by template name;  
   - There are multiple templates in the primary list titled `ENA -  XXXX` 
   - Typing `ENA` in search bar turns up 0 results
   - Typing `ENA -` in search bar now turns up just one of the results

   
   
**Screenshots example 1, template search**

For several templates named `ENA - ...` we see there are several in the llist of templates:

![image](https://github.com/user-attachments/assets/b929c98e-4dcb-4652-aa7f-c41df7004911)

However when we enter `ENA` in the search box we get no results:

![image](https://github.com/user-attachments/assets/cf9ac7fb-eeb4-43ce-9a0b-40f908381b5e)

And when we type `ENA - ` in the search bar we get one of them as a result:

![image](https://github.com/user-attachments/assets/f88d1b91-9f79-43af-8f8a-5bb8b657c2f3)

**Comment by Freymaurer** [comment]
Hey! Could you pls open two issues for this? As the two problems you describe are not related to each other. Feel free to keep this one for Template search and open another one for term search.

**Comment by shiltemann** [comment]
done :+1:

**Comment by Freymaurer** [comment]
The reason behind this behavior is our search algorithm. We use sorensen dice on string bigrams. A lot of fancy words for "we look for similiarity and the more similiar the two strings we compare the higher the score", and to filter out unfit results we apply a threshold. In your example "ENA - " has actually more similiarity to `SRA - Sequencing` than to the longer ENA names. For example in "ENA - ~~Gene promoter annotated sequence~~", we have ~30 missmatch characters. In "~~SRA~~ - ~~Sequ~~en~~cing~~" we have only 11 missmatch characters. This very flexible calculation allows for semi-similiar result search. To avoid your described issues we know adjust the score as follows:

- Increase score drastically if it starts with query (+0.5)
- Increase score if contains query (+0.3)

> [!NOTE]
> Threshold is 0.3

![Image](https://github.com/user-attachments/assets/a8ed5fa7-67ec-4d9d-9603-a6ad182abbb2)
