### ISSUE TITLE
[Bug]: Improve term search functionality

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/Swate#491]
### What happened?

When searching ontology terms in ARCitect , the search results are sometimes suboptimal.

Example:
-  searching for `single` turns up a result titled single-end
- but if we had entered the entire term `single-end` no results show up
   
**Screenshots**

searching for `single` turns up a `single-end` result

![image](https://github.com/user-attachments/assets/6f134850-cd2e-4e65-b6e4-f569d6086d25)

but searching for `single-end` as a complete term turns up no results:

![image](https://github.com/user-attachments/assets/1ce27595-5452-455b-a579-9b821ad0927f)

### Host

Applies to All

### Host Details

 - OS: Ubuntu 22.04
 - ARCitect version: v0.0.40

### Swate version

ARCitect v0.0.40

**Comment by Freymaurer** [comment]
I looked into this issue and found the problem. I use cypher full text search to query the database on term names. This full text search supports apache lucene syntax and a `-` is interpret as "MUST not contain the following". I added logic to escape all apache lucene special characters now, which solves this issue 👍 Will be live with the next release (somewhen today)

**Comment by Freymaurer** [comment]
![image](https://github.com/user-attachments/assets/d3ee7e63-9ace-4b84-9543-5010c7308b39)
