### ISSUE TITLE
[Feature Request][Excel]:  Button for creating metadatasheet

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#507]
### Is your feature request related to a problem?

In Swate Alpha, you can create a new file, having the option to select between Assay and such. In Excel, this would make no sense, as you're already inside a specific file.

### Describe the solution you would like!

If you're in a file where there is no metadata sheet, you should be given to option to add such a sheet, choosing between Assay, Study, Investigaiton and Template.

### Host

Excel

### Host Details

Swate for Excel

**Comment by Etschbeijer** [comment]
Will be solved in the Issue #510.
