### ISSUE TITLE
[Feature Request]: Rename or describe RO-Crate in file export

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#508]
### Is your feature request related to a problem?

![image](https://github.com/user-attachments/assets/9e84d7ac-1c17-4ebe-a870-f22bce94e00c)

When exporting to json, you're given an option, which format you want to export to. ROCrate is one option here.

### Describe the solution you would like!

First of all, ROCrate is actually written as `RO-Crate`.

Second, I'm not sure whether RO-Crate is the correct name for the file here, as a single metadata file does not result in an actual RO-Crate (which would be the zip-archive with a full metadata file).

Therefore I propose we make this a bit more clear by either renaming this to `Json-LD`, which might be a bit too broad, or ISA-RO-Crate, to actually incorporate the info that we're talking about the ISA profile. 

@floWetzels 

### Host

Applies to All

### Host Details

All

**Comment by Freymaurer** [comment]
Any new information on what name to use? @HLWeil @floWetzels ?

**Comment by floWetzels** [comment]
Sorry, only seeing this now. How about simply "RO-Crate Metadata"? That's what it is, right?

**Comment by HLWeil** [comment]
> Sorry, only seeing this now. How about simply "RO-Crate Metadata"? That's what it is, right?

Also seems sensible 👍

**Comment by Freymaurer** [comment]
Done, will be live with the next release
