### ISSUE TITLE
Add "unique identifier" for column names

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#52]
As it is, we cannot add a column with the name of an already existing column. To circumvent this we need a unique identifier.

I first thought of actual Guids but the result bloated the column width too much to allow for effortless working on the table.

Example: 
`Parameter [instrument model; #75e44bc6-f5b3-4bbc-874b-1fd76a78129f]`

So i went with the approach to test the column headers for the new-would-be-name and if it exists i go one up for the id.
Example:
![grafik](https://user-images.githubusercontent.com/39732517/98987737-eff92680-2526-11eb-9aa2-5eb23337e995.png)

The logic behind this creates a name with id 0 (will not be shown) and if it finds this name in the table it will loop over the name creation with (previousId+1). To circumvent any problems with the hidden column names, it also checks for those.

**Comment by kMutagene** [comment]
Hey @Freymaurer, fair point. It really looks like we have to set some properties in the column header. I would suggest putting these after the bracket in another one to preserve readability and similarity to the strict ISA annotations like this:

```
Parameter[instrument model]
Parameter[instrument model] (#2)
SomeHiddenCol[someAnnotaton] (#hide)
SomeHiddenCol[someAnnotaton] (#2, #hide)
```

Also, i think starting to count at 2 is mor eintuitive in this case.

**Comment by Freymaurer** [comment]
Good Point! This actually helped reducing the "parsing complexitity". I changed it to the new "xx [x] (#a; #b)" format/style.
