### ISSUE TITLE
[Bug]: DPBO links still don't work

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/Swate#520]
### What happened?

For DPBO terms, Swate still links to purl.obolibrary.org/obo/DPBO... , which do not exist. purls for DPBO terms have the format http://purl.org/nfdi4plants/ontology/dpbo/ . This was already changed here: https://github.com/nfdi4plants/ARCtrl/pull/381 so I thought it should work now.

### Host

Standalone

### Host Details

firefox

### Swate version

v1.0.0-beta.08

**Comment by Freymaurer** [comment]
Hey! Thanks for the feedback. i just got back and will investigate this issue!

**Comment by Freymaurer** [comment]
Should be using the correct links now!

E.g.: http://purl.org/nfdi4plants/ontology/dpbo/DPBO_1000127

Altough the link seems dead to me?

Will close for now, feel free to reopen should this not be the correct link 🙂

**Comment by StellaEggels** [comment]
Great, the whole purl archive seems to be down at the moment, hopefully once they fixed that the links will work.
