### ISSUE TITLE
[Feature Request]: Swate, Excel, Enable matching terms when button "Validate/ Update Ontology Terms" is clicked

### ISSUE THREAD

**Issue by Etschbeijer** [nfdi4plants/Swate#522]
### Is your feature request related to a problem?

Currently, the "Validate/ Update Ontology Terms" button deletes the values of the property columns when the main column or unit is empty.

### Describe the solution you would like!

When clicking the "Validate/ Update Ontology Terms" button and the main / unit column contains values, the propertie columns are checked and updated with the right values, depending on the value in the main column

### Host

Applies to All

### Host Details

Excel

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Etschbeijer** [comment]
@Freymaurer Hello, here are the requested details for the implementation of a perfect match query that can be used in ARCTable:
Create a method in ARCTable that can request a perfect Match term based in its Id (string).
Requested part of you: An API, that uses a string array as input and return an array of Some ontologyanotations, based on Perfect Match.
