### ISSUE TITLE
[Bug]: The input widgets that are created with the (+) button have different heights

### ISSUE THREAD

**Issue by Etschbeijer** [nfdi4plants/Swate#524]
### What happened?

The input widgets that are created with the (+) button have different heights.
![Image](https://github.com/user-attachments/assets/4fc85a7e-4d8a-4933-b41b-ac61b6843a8a)

### What did you expect?

The input widgets that are created with the (+) button should have the same height.

### Host

Applies to All

### Host Details

Browser (Mozilla)

### Swate version

1.00 alpha

**Comment by Freymaurer** [comment]
Fixed!
