### ISSUE TITLE
[BUG] Data Annotator button missing in Datamap

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#528]
**OS and framework information (please complete the following information):**
 - OS: Windows 11
 - ARCItect Version 0.0.46

**Describe the bug**
DataAnnotator Button in Swate Alpha:

![image](https://github.com/user-attachments/assets/72551a8d-966e-46de-b623-47cd8d5f5a2b)

Missing in ARCItect

![image](https://github.com/user-attachments/assets/e71dc0bd-3f9f-4a07-8b64-e4413667645e)

**Comment by Freymaurer** [comment]
Done!
