### ISSUE TITLE
[Bug]: CSV fragment selector indices should be 1-based and count headers

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#529]
### What happened?

Data fragment indices created by Data Annotator tool should be 1-based and headers should ne be ignored. See [rfc-7111](https://datatracker.ietf.org/doc/html/rfc7111#section-2.1)

So in the given example:

![image](https://github.com/user-attachments/assets/55a48af6-5901-48c3-a3cf-eb0e29d9a43d)

I selected the first non-header row, which is the second row of the file.

Therefore the correct fragment selector would be row=2 but is:

![image](https://github.com/user-attachments/assets/8e24facb-9b59-47ee-8728-7cfc7e64c598)

### Host

Applies to All

### Host Details

Windows11 
https://swate-alpha.nfdi4plants.org/

### Swate version

?

**Comment by Freymaurer** [comment]
Done! Should be live soon!

**Comment by HLWeil** [comment]
Thanks a lot for your timely fix!

Just noticed that selectors for Colulms are 0-based. They should also be one-based. And the same is true for the cells.

![image](https://github.com/user-attachments/assets/92c687a0-126a-41b6-a025-a589ad11d7dc)

**Comment by Freymaurer** [comment]
Fixed! Very sorry about the oversight, was very stressful yesterday
