### ISSUE TITLE
[Feature Request] provide function to change the order of defined contacts 

### ISSUE THREAD

**Issue by arendd** [nfdi4plants/Swate#535]
**Is your feature request related to a problem? Please describe.**
Usually researcher are interested in defining a specific author order. Currently one can not change the order of the contacts without deleting exisiting ones, e.g. adding a contact in the middle means deleting the last contacts and adding them again. 

**Describe the solution you'd like**
Maybe some simple  "+" and "-" buttons to move the contacts in the list up and down

**Comment by Freymaurer** [comment]
I added general logic to all form lists to use a reorder drag and drop logic! Will be live soon
