### ISSUE TITLE
[BUG] Displayed IRIs in Swate still incorrect

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/Swate#537]
**Describe the bug**
When I search for terms (e.g. `extraction buffer`, a DPBO term), and I want to click the link I still get an error message. When I check the URL, I see that there are still the `purl.obolibrary.org` links used, instead of the `purl.org` links. The same is true for other ontologies such as EFO for example, that don't use obolibrary purls.

**To Reproduce**
1. Open Swate: https://swate-alpha.nfdi4plants.org/
2. Open the right-hand menu and go to `Ontology term search`
3. Type in either `extraction buffer` (DPBO:0000050) or `family relationship` (EFO:0004424)
4. Click on the term link

**Expected behavior**
For `extraction buffer` I expected to be lead to the URL `http://purl.org/nfdi4plants/ontology/dpbo/DPBO_0000050`
For `family relationship` I expected to be lead to the URL `http://www.ebi.ac.uk/efo/EFO_0004424`

**Related issues/PRs**
This was previously discussion in issue nfdi4plants/ARCtrl#368 
The corresponding PR from that time is nfdi4plants/ARCtrl#381 

**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox

**Additional context**
Currently (17.10.2024) the internet archive is still under attack which hosts the "expected" purls (purl.org), so ATM none of the expected DPBO links should work until that is resolved.

**Comment by Freymaurer** [comment]
Yes this was an oversight on my side. I was still using a pre ARCtrl function, therefore it did not update automatically. Should be fixed now 😞 🐛
