### ISSUE TITLE
[Feature Request]: Excel, enable easy check of term information

### ISSUE THREAD

**Issue by Etschbeijer** [nfdi4plants/Swate#538]
### Is your feature request related to a problem?

Currently it is not possible to send a single or array of term names to the database and return a collection of the associated term source refs and accession numbers.

### Describe the solution you would like!

Send a single term name or collection of term names to the database and return a associated collection of term source refs and accession numbers, when the name is fitting. Otherwise return nothing.

### Host

Applies to All

### Host Details

Excel

**Comment by Freymaurer** [comment]
this has been resolved. `Api.ontology.searchTerms` should fit this usecase!
