### ISSUE TITLE
[BUG] flickering annotation table 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#542]
A user reported a flickering screen with swate in ARCitect
- Not sure, whether ARCitect or Swate issue
- ARC is stored locally (not server or cloud)  
- occurs on multiple ARCs

https://github.com/user-attachments/assets/42c7f112-52fe-4acc-b5a2-30ef3980b632

 - OS Windows 11 Pro
 - ARCitect v0.0.48

**Comment by frsommer** [comment]
Same Problem here,
it occurs when i have long cell inputs, that go over 2 lines and then scrolling down.

Sometimes file/directory-path seems too long for a cell, is overwriting the next one:
![image](https://github.com/user-attachments/assets/6a939166-2b61-4732-9d0c-7f2dcb7c6350)
W10, arcitect 0.48

**Comment by Freymaurer** [comment]
Will tackle this issue soon!

**Comment by Freymaurer** [comment]
Closed will be tracked in #567
