### ISSUE TITLE
[Feature Request]: add clickable link to ontology

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#544]
### Is your feature request related to a problem?

Would help a lot to have a link to added terms in the Source Ontology.

### Describe the solution you would like!

I'd suggest to add this to the details widget

![Screenshot 2024-10-25 at 10 40 42](https://github.com/user-attachments/assets/67b60b70-0500-4e84-972a-10a3230e28ce)

### Host

Applies to All

### Host Details

all

**Comment by Freymaurer** [comment]
> Would help a lot to have a link to added terms in the Source Ontology.

Sorry i don't quite understand 😞

**Comment by Brilator** [comment]
How can I go from above swate annotation table to http://purl.obolibrary.org/obo/NCBITaxon_3702?

**Comment by Freymaurer** [comment]
ahh okay, now i understand! Will do!

**Comment by Freymaurer** [comment]
Done! Will be part of the next release!
