### ISSUE TITLE
[Bug]: cannot add free text to cells

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#556]
### What happened?

Cannot add free-text (non-ontology) data. 
When typing any free text in cell and hitting enter, the values just disappear. 

### Host

Applies to All

### Host Details

all

### Swate version

Swate Release Version v1.0.0-beta.14

**Comment by Brilator** [comment]
@Philipp-CMML

**Comment by shiltemann** [comment]
Thanks @Brilator, Julia Voelker and I noticed this during the workshop last week too. But it was working the week before that when I was preparing materials for the workshop, so likely due to a recent change.

**Comment by Freymaurer** [comment]
Fixed! Will be live with the next release
