### ISSUE TITLE
[Feature Request]: UX copy / paste 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#563]
### Is your feature request related to a problem?

From workshop: 
> selecting columns/rows like possible in excel would be soo much easier for copying and pasting

### Describe the solution you would like!

selecting columns/rows like possible in excel would be soo much easier for copying and pasting

### Additional context!

I know that's not trivial. 

### Host

Applies to All

### Host Details

all

**Comment by Freymaurer** [comment]
Closed, tracked in #567
