### ISSUE TITLE
[Bug]: buttons on top are displaced in ARCitect

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#564]
### What happened?

<img width="256" alt="Screenshot 2024-11-13 at 10 16 37" src="https://github.com/user-attachments/assets/7d430a33-944a-4f1c-ac9c-8541269555bd">

### What did you expect?

.

### Host

ARCitect

### Host Details

ARCitect v0.0.49

### Swate version

Swate Release Version v1.0.0-beta.15 Host ARCitect

**Comment by Freymaurer** [comment]
Swate beta.16 was just released and should fix a lot of visual issues!
