### ISSUE TITLE
[Bug]: UX trigger filling cells 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#565]
### What happened?

From workshop
> Having to double-click on a cell before typing is against muscle memory acquired from excel

### What did you expect?

Type and directly write value 

### Host

Applies to All

### Host Details

all 

### Swate version

Swate Release Version v1.0.0-beta.15 Host ARCitect

**Comment by Freymaurer** [comment]
Closed, tracked in #567
