### ISSUE TITLE
[Bug]: Update column has no box

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#569]
### What happened?

And also no button to click update

![image](https://github.com/user-attachments/assets/a9d06726-1696-4e4f-a96e-9b7c9c84f596)

### Host

ARCItect 0.0.49

### Swate version

recent

**Comment by Freymaurer** [comment]
Ups missed that one, will be fixing that immediately

**Comment by Freymaurer** [comment]
Fixed! will be live with the next release
