### ISSUE TITLE
[Bug]: Import local template is broken

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#570]
### What happened?

When selecting a file for import, the box is missing:

![image](https://github.com/user-attachments/assets/4ec7e139-a328-4ae9-8c05-3d9b4e18a48f)

### Host Details

ARCitect 0.0.49

### Swate version

recent

**Comment by HLWeil** [comment]
Works now! Will reopen for a minor bug.

When you select "Import Metadata". The option to Import specific processes is greyed out and they won't be imported like this.

![image](https://github.com/user-attachments/assets/5556868d-8f9f-4824-a231-c40c02b066d2)

In order to import everything, you have to unselect assay metadata import and first select all processes, then select the assay metadata again.

**Comment by Freymaurer** [comment]
I noticed this issue as well and fixed it!
