### ISSUE TITLE
[Bug]: Ontology search names are cutoff unpractically (found in Datamap)

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate#572]
### What happened?

Found this in Datamap, not sure if it happens elsewhere:

![image](https://github.com/user-attachments/assets/28aa36d3-bbed-48d3-baac-1d7702a59fdc)

### Host Details

ARCitect 0.0.49

### Swate version

recent

**Comment by Freymaurer** [comment]
you can hover for the name to appear as tooltip. But i also set a min width of 400px now.
