### ISSUE TITLE
[Bug]: ORCID search + manually additing don't work together 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#575]
### Contact Details

sabrina.zander@hhu.de

### What happened?

Contacts: 
If I search for a person via ORCID, confirm the person and then want to add further information  (such as email, affiliation...), all the information from the ORCID search is gone.

Steps to reproduce:
1. Search for person via ORCID, e.g. 0009-0000-4569-6126
2. Add email/affiliation etc.
3. First and last name are gone

### Host

Applies to All

### Host Details

Windows 11
ARCitect v 0.0.50

### Swate version

 v1.0.0-beta.18

**Comment by Freymaurer** [comment]
Found the issue and fixed it! Will be live with the next release!
