### ISSUE TITLE
[Bug]: Copy entire rows

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#576]
### Contact Details

sabrina.zander@hhu.de

### What happened?

I want to copy an entire row of a Swate table. This is not possible at the moment.

### What did you expect?

Should be possible by right clicking on the row number, copying it and pasting everything into the new row.

### Host

Applies to All

### Host Details

Windows 11, ARCitect 0.0.50

### Swate version

 v1.0.0-beta.18

**Comment by Freymaurer** [comment]
Closing this here, will be tracked in #567
