### ISSUE TITLE
[Feature Request] Keep sheet-order of imported json isa

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/Swate#577]
**Is your feature request related to a problem? Please describe.**
importing e.g. an assay json isa, selecting the different "sheets", does not order them like they were when exported (also listed in the correct order in the selection-pop-up)

**Describe the solution you'd like**
keep the order of the different sheets like chosen

**Describe alternatives you've considered**
always have to import and then move them to the correct position for stupid order-fanatic guys like me

exported:
![image](https://github.com/user-attachments/assets/52c3405f-d5fa-4afa-b5ad-b9c20c7eeffe)

Imported:
![image](https://github.com/user-attachments/assets/96f55cbd-5000-45cf-819d-bbc4331be609)

**Additional context**

**Comment by Freymaurer** [comment]
Hey, can you give me the file in question for this? So i can check it out?

**Comment by Freymaurer** [comment]
I tried to replicate this issue with the file below, but everything was working as expected 🙁 

[20241121_093316_isa.assay.xlsx](https://github.com/user-attachments/files/17843372/20241121_093316_isa.assay.xlsx)

**Comment by frsommer** [comment]
[20241120_105020_RedOxGRX10percentR3R5.json](https://github.com/user-attachments/files/17843733/20241120_105020_RedOxGRX10percentR3R5.json)

here is the last i tried, maybe mzy workflow is wrong?
open the new assay, add a new sheet, klick the right lower arrow for swate, klick import, assay isa, select exported json file from menu, klick import with data, and select the sheets to import. in the selection menu the sheets are well ordered, in the imported assay the tabs are exactly in opposite order

**Comment by frsommer** [comment]
i mean:
he right lower arrow for swate, klick **templat**e, import, assay is

**Comment by Freymaurer** [comment]
Ahh i see! Yes, found the issue and fixed it! Will be live with the next release!
