### ISSUE TITLE
Use DataPLANT and Swate logos/socials

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#59]
Logos: 
	- [DataPLANT](https://github.com/nfdi4plants/Branding#dataplant)
	- [Swate](https://github.com/nfdi4plants/Branding#swate)

Socials:
	- [DataPLANT twitter](https://twitter.com/nfdi4plants)

**Comment by Freymaurer** [comment]
Which icon should be used for the manifest.xml as entry point for Swate? 

![image](https://user-images.githubusercontent.com/39732517/105959937-d6bf3b00-607c-11eb-9a75-e77886245847.png)

And of course we need scaled down versions of this icon.

**Comment by Freymaurer** [comment]
I think the transparent option could need some improvements.

![image](https://user-images.githubusercontent.com/39732517/105960517-9f9d5980-607d-11eb-9825-e27b594651df.png)

As the lighter bars of the "E" are in fact not transparent but white and it looks... well strange.

**Comment by kMutagene** [comment]
That is by design, we need one for a dark background as it definitely does not look good on the dark green. The logos are a different story, I'll fire up Affinity designer and get back to you tomorrow.

**Comment by kMutagene** [comment]
Alright, so i designed [this logo](https://github.com/nfdi4plants/Branding/blob/master/logos/Swate_logo_for_excel.svg) to look good on the excel darkgreen and added all icon sizes [here](https://github.com/nfdi4plants/Branding/tree/master/icons)

**Comment by Freymaurer** [comment]
I have some additional questions about the color palette. 
- Are these colors meant to extend the excel color scheme used? Let's say e.g. for buttons ands links?
- If the first question is answered with yes then we could really need a red tone for similiar use as "isDanger" in Bulma.
- And looking into the future we could need also need Branding/Logo/Color for Spawn.

Let me hear what you think about this @kMutagene

**Comment by kMutagene** [comment]
here are monoline guidelines for office icons:
https://docs.microsoft.com/de-de/office/dev/add-ins/design/add-in-icons-monoline
