### ISSUE TITLE
Handle Column groups

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#6]
Columns and their term source references and/or associated other columns (such as units) have to be grouped or at least created as groups when inserting them.

Current plan:
- [x] Create Term Source REF and  Term Accession Number Columns for every annotation column
- [ ] Make these columns Hidden and read-only

**Comment by Freymaurer** [comment]
i just noticed this issue and this was implemented with PR #34, but the additonal columns are not read-only yet. Will add this with the next PR.

**Comment by kMutagene** [comment]
Hidden should be enough
