### ISSUE TITLE
[BUG] create annotation table fails if whole Row(s) is/are selected

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#63]
**Describe the bug**
If one selects one or several rows when creating the annotation table, the application fails.

**To Reproduce**
1. Select one or several rows (Click on the row names for this, e.g. row A to C)
2. Click on 'create annotation table'
3. See error

**Expected behavior**
Since creating a table into column eternity (1 048 576 columns) may not be a viable option, it would be good to have a fixed limit for this (e.g. 100 rows).

**OS and framework information (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - OS Version 10.0, Build 18363
 - MS Excel: Excel Desktop
 - MS Excel version 2008 (Build 13127.20760)

**Additional context**
This error seems to occur much more often if the system is under stress.

**Comment by kMutagene** [comment]
I don't think we need to support selecting rows or columns as annotation table, as the concept of the annotation table itself indicates that it is finite. But we should cover this eventually in tutorials/videos etc.

**Comment by Freymaurer** [comment]
Added a small check to only add 20 rows if a whole row is selected! This will be live in version 0.2.1.
