### ISSUE TITLE
[BUG] In advanced search: Field 'select ontology' is missing in drop-down menu after selecting an ontology

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#64]
**Describe the bug**
If using advanced search in TermSearch and selecting an ontology, it can not be switched back to 'select ontology', thus it is not possible to search for all ontologies without cancelling and restarting the advanced search again.

**To Reproduce**
1. Go to 'TermSearch'
2. Insert anything into the search field
3. Click on 'Use Advanced Search'
4. Click on 'select ontology'
5. Choose an ontology from the drop-down menu
6. Click the field again
7. In drop-down menu, no 'select ontology' can be found

**Expected behavior**
'select ontology' should reappear again.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47781170/100770201-4c03ec00-33fd-11eb-84a4-84c13c881276.png)
'select ontology' field before selecting an ontology.

![grafik](https://user-images.githubusercontent.com/47781170/100770294-650c9d00-33fd-11eb-9c77-2e6f1afd399c.png)
No 'select ontology' anymore after an ontology was selected.

**OS and framework information (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - OS Version 10.0, Build 18363
 - MS Excel: Excel Desktop
 - MS Excel version 2008 (Build 13127.20760)

**Comment by Freymaurer** [comment]
Fixed, will be part of the next release (0.1.3).
