### ISSUE TITLE
[BUG] Page 1 button is shown twice if advanced search finds few search results

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#65]
**Describe the bug**
If advanced search finds enough results to show them on one page, page number is shown twice.

**To Reproduce**
1. Go to TermSearch
2. Insert anything into the search field
3. Click on 'Use Advanced Search'
4. Click on 'Term name keywords'
5. Insert anything into the search field that leads to result few enough to display them on 1 page
6. See bug

**Expected behavior**
Only 1 page number (or none) should be displayed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47781170/100783244-cfc5d480-340d-11eb-8044-41d0dd4c98a2.png)

**OS and framework information (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - OS Version 10.0, Build 18363
 - MS Excel: Excel Desktop
 - MS Excel version 2008 (Build 13127.20760)

**Comment by Freymaurer** [comment]
Fixed, plus added a disabled property to the "prev" and "next" button if there is no previous or next pagination (e.g. first and last page).
