### ISSUE TITLE
[BUG] If search text field is active, textcursor is always set to the end of the text if a letter is added

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#66]
**Describe the bug**
If search text field is active, the textcursor is always set to the end of the text if a letter is added.

**To Reproduce**
1. Go to 'TermSearch'
2. Click on the text field, insert a word, move the textcursor to the beginning of the word
3. Add a letter
4. Textcursor is moved to the end of the word

**Expected behavior**
Textcursor stays at the expected position (1 character further than before)

**OS and framework information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - OS Version [e.g. 1809] 
 - MS Excel: [e.g. Excel Desktop, Excel Online]
 - MS Excel version [only for Excel Desktop]

**Comment by Freymaurer** [comment]
Fixed!
