### ISSUE TITLE
[Feature Request] Linked IRI in TermSearch

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#69]
**Is your feature request related to a problem? Please describe.**
When using TermSearch to search for ontology terms (e.g. "seedling development stage"), it would be helpful to have the 
term IRI (http://purl.obolibrary.org/obo/PO_0007131) clickable to look up annotations (in addition to the term definition on hover-over info icon). 

**Describe the solution you'd like**
Info-icon on the left in TermSearch hyperlinked to Ontobee / IRI. 

**Describe alternatives you've considered**
Term id in the right column (e.g. "PO_0007131") hyperlinked to Ontobee / IRI.

**Comment by Freymaurer** [comment]
Fixed! Made id on the right to clickable links.

![image](https://user-images.githubusercontent.com/39732517/100940390-24de1500-34f8-11eb-952e-de70475be6df.png)
