### ISSUE TITLE
[BUG] Search results from "Advanced Search" are not selectable

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#70]
**Is your feature request related to a problem? Please describe.**
In order to use a term found via "Advanced Search", I need to copy paste the term from there to the original search field in AddBuildingBlock or TermSearch. 

**Describe the solution you'd like**
Would be nice to have search results selectable directly from "Advanced Search" (same behavior as the original search - select). 

**Describe alternatives you've considered**
Expand list of suggested terms to display more than the five (best matches) - maybe as a list to scroll.

**Comment by kMutagene** [comment]
Hey @Brilator, thanks for your suggestions!

>Expand list of suggested terms to display more than the five (best matches) - maybe as a list to scroll.

I definitely agree with this. We should add a dropdown or input field that makes it possible to adjust the amount of items displayed here. cc @Freymaurer

**Comment by Freymaurer** [comment]
> In order to use a term found via "Advanced Search", I need to copy paste the term from there to the original search field in AddBuildingBlock or TermSearch.

Good you mentioned this, as it actually was intended. Must have broken down at some point.

**Comment by Freymaurer** [comment]
Fixed! You will now be able to confirm you choice correctly and fill fields with it.

> Expand list of suggested terms to display more than the five (best matches) - maybe as a list to scroll.

For now i would aks you to open a new issuefor this.
