### ISSUE TITLE
[Feature Request] Search by term accession number

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#71]
**Is your feature request related to a problem? Please describe.**
There may be rare cases where people already worked with ontologies and have some (non-SWATEd) tables with ontology terms and accession numbers. It could help to allow searching by the accession numbers / IRIs. 

**Describe the solution you'd like**
Add search for term accession number (to Advanced Search).

**Comment by Freymaurer** [comment]
Done! Swate will now try to parse any input to a accession value, if the parse succeeds the database is searched by accession.
![image](https://user-images.githubusercontent.com/39732517/102338325-fcdcc000-3f93-11eb-884e-508df0238f37.png)

This search option only works with just the accession value, even a whitespace after the value will disable it.

This function will be part of the next release.
