### ISSUE TITLE
Properly Document Office interop functions

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/Swate#75]
There are a plethora of functions that have all kinds of effects on the excel sheet in the `OfficeInterop` module , but most of them are undocumented.

Office interop is the most complicated part of this project, as it is using the Javascript promise syntax in F#. Extensive inline documentation of what is happening would be beneficial.

**Comment by Freymaurer** [comment]
I added inline comments to most interop functions and also remodelled some functions to improve readability.
