### ISSUE TITLE
[Feature Request] Add sql dump including second ontology set.

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#78]
**Is your feature request related to a problem? Please describe.**
As we decided to add new ontologies to the swate db (https://github.com/nfdi4plants/nfdi4plants_ontoloy/milestone/1), we need a sql dump for development. 

**Describe the solution you'd like**
The best option would be to just update the sql dump file, but with over 2 million new terms and as many new isA relationships it is now to big to be uploaded to github directly. I would propose to leave the sql dump file and add a extended version with all new ontologies as a .zip file (~39mb). 

**Describe alternatives you've considered**
We could also look for an alternative file host. Maybe we could use the HUBzero environment for this? @kMutagene

**Comment by kMutagene** [comment]
Take a look at [git lfs](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/versioning-large-files). Its 1 GB free for organizations on github, although im not sure how to set it up for the org (maybe you could dig a little into that). On the long term, things like this will most likely be put on DataPLANT storage that we can access via a tool like git lfs or equivalent.

**Comment by kMutagene** [comment]
However, please stop tracking the dumps in this repo if it is becoming that large. We should put it into the SwateDB repo

**Comment by kMutagene** [comment]
If it does not destroy your workflow and if that dump was your last commit, you can reset to one commit before and force push to remove it

**Comment by Freymaurer** [comment]
SQL dumps are reduced to only consist of template-related table and the ontology table, while terms are bulk inserted, via the new SwateDB Scripts.
