### ISSUE TITLE
[BUG] Unable to find term, although it's in SwateDB. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#88]
**Describe the bug**
I'm trying to add the term "plant growth medium exposure" using SWATE. 
I know it's in the SwateDB https://github.com/nfdi4plants/SwateDB/tree/master/projects/obo2sql/data/peco.obo. 

Using advanced search for the _term name keywords_ "plant growth medium exposure" yields 222 pages for all or 88 pages limited to PECO, respectively (which I did not check all). 
When using _name must contain_, I don't get any term for "plant growth medium exposure".

**To Reproduce**
1. Go to advanced search
2. Search for "plant growth medium exposure"
3. Try to find the term.

**Comment by Freymaurer** [comment]
Hey, sry for the late answer! I looked into it and found an empty entry for the id "PECO:0007147" 
![image](https://user-images.githubusercontent.com/39732517/105483820-b4a77080-5caa-11eb-91f7-c0df4f8af656.png)

Will try to find out how this happenend and will keep you updated!

**Comment by Freymaurer** [comment]
So i tried to add the term with my previously used functions to a development database and everything worked fine. I will now try to this with the whole peco ontology and see if i can find any problems. If not i will transfer it to the production database.

**Comment by Freymaurer** [comment]
Okay i did update the production database with the whole peco ontology again. I wasn't able to figure out how this term was not inserted, so please feel free to report any missing terms!

This change is live from now on!

**Comment by Brilator** [comment]
Thanks, works. Also good to see that (and how) you can search for terms by id.

**Comment by Freymaurer** [comment]
A search option by accession number was added in release 0.2 as it was requested [here](https://github.com/nfdi4plants/Swate/issues/71#issuecomment-746079444). If we can do anything else, do not hesitate to write us!

**Comment by Brilator** [comment]
True, but you have to use exact search, i.e. "PECO:0007147" will do - "PECO 0007147" will not. Actually, the search engine might be worth its own issue.

**Comment by Freymaurer** [comment]
@Brilator Yes, please open a new issue where we can discuss possible search options via the term accession number!
