### ISSUE TITLE
[Feature Request] New ontologies required for PRIDE submission

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#89]
**Is your feature request related to a problem? Please describe.**
PRIDE submission requires several ontologies for specific terms.

**Describe the solution you'd like**
Those ontologies should be uploaded in respect to the proteomics template.
The ontologies are:
- NEWT (UniProt Taxonomy database)
- The BRENDA Tissue Ontology (BTO)
- Cell Ontology (CL)
- Human Disease Ontology (DOID)
- Protein modification (PSI-MOD)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Freymaurer** [comment]
Would you mind opening these issues [here](https://github.com/nfdi4plants/nfdi4plants_ontoloy) just so we have everything noted at the correct position? Thanks a lot!

**Comment by kMutagene** [comment]
@Freymaurer note that you can transfer issues between repositories of an organization, but in this case it is better to fill the respective issue template anyways.
