### ISSUE TITLE
[Feature Request] Full names of ontologies in Advanced Search

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#90]
**Is your feature request related to a problem? Please describe.**
When using Advanced Search, ontologies shown in the "select ontology" dropdown menu are abbreviated. 

**Describe the solution you'd like**
It might be nice if the full names of these ontologies are visible when, examplarily, hovering over them.

**Describe alternatives you've considered**
Show full names with abbreviations in brackets.

**Additional context**
Screenshot:
![grafik](https://user-images.githubusercontent.com/47781170/105865069-da0de480-5ff2-11eb-9bf5-7cca53209856.png)

**Comment by Freymaurer** [comment]
Please correct me if i am wrong, but this is already possible by hovering over the info icon on the left.

![image](https://user-images.githubusercontent.com/39732517/105946105-dcaa2180-6066-11eb-92be-001d6c75c746.png)

If you think this needs to be shown in another way, please let us know!
