### ISSUE TITLE
[Feature Request] Make Advanced Search available by default

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#91]
**Is your feature request related to a problem? Please describe.**
...without having to search a term first. 

**Describe the solution you'd like**
1. Open SWATE (CSBAnnotator) 
2. In "AddBuildingBlock" or "TermSearch" directly get the option to "Use Advanced Search" 

**Describe alternatives you've considered**
Add "Advanced Search" as additional tab, but the tab bar is getting big already.

**Comment by Freymaurer** [comment]
This is an excellent idea!What do you think about this simple solution?

![image](https://user-images.githubusercontent.com/39732517/105947630-bcc82d00-6069-11eb-97c5-547045d77af0.png)

This will also be added for term search and will be live in version 0.2.1
