### ISSUE TITLE
[BUG] More ontologies than UO are choosible when 

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#93]
**Describe the bug**
When adding a unit to a new building block, terms from other ontologies than Unit Ontology (UO) are allowed.

**To Reproduce**
(See Screenshot)

**Expected behavior**
Only UO terms are allowed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47781170/105921931-e79a8d00-6039-11eb-84a7-a0639a7a0d22.png)

**OS and framework information (please complete the following information):**
No.

**Comment by Freymaurer** [comment]
Done! This change will be live in version 0.2.1!
