### ISSUE TITLE
[Feature Request] "Add unit" function in "Add Building Block" section

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#94]
**Is your feature request related to a problem? Please describe.**
When adding a Building Block section which will have a specific unit you don't know yet, it is not possible to later add or change the unit.

**Describe the solution you'd like**
An "Add unit" function (button) that allows you to add a specific unit to an already created Building block.

**Comment by Freymaurer** [comment]
Added option to add unit reference columns to building block without prior unit reference columns.

![image](https://user-images.githubusercontent.com/39732517/105991153-c078a580-60a3-11eb-9627-de4508cd8e16.png)

This feature will be live in 0.2.1!
