### ISSUE TITLE
[Feature Request] Make info for existing building blocks easily available. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#96]
**Is your feature request related to a problem? Please describe.**
When looking at previously built annotation tables (e.g. shared by others), it would be good to get the extra info (e.g. description) for the linked term. 

**Describe the solution you'd like**
Similar to the "related term directed search", which builds on the linked term, it would be good to find the info (ontology, term id, description) e.g. in the same TermSearch panel / tab. 
This way people can double-check, wether the supplied annotation fits.

**Comment by Freymaurer** [comment]
Which information exactly would you like to be displayed?

**Comment by Brilator** [comment]
ontology, term id, and most importantly description (i.e. the same as hover-over the info icon during search).

**Comment by Freymaurer** [comment]
Done! Added a button to display avaiable building block information.

![image](https://user-images.githubusercontent.com/39732517/108826200-4f55e080-75c4-11eb-8dc0-99937f7f609f.png)

<hr>

![image](https://user-images.githubusercontent.com/39732517/108826235-57ae1b80-75c4-11eb-94be-07c78751f04f.png)

<hr>

This will be part of version 0.4.0!
